# Welcome to the PGC Video Training Textbook!

```{r, echo=FALSE}
library("vembedr")
embed_url("https://youtu.be/CMhYrXd1riA")
```

Hello! I'm Cathryn Lewis from King's College London, and I'm the Education and Training lead for the Psychiatric Genomics Consortium. I'm very pleased to welcome you to the PGC's Video Training Textbook.

The aim of the textbook is to provide comprehensive training materials in psychiatric genetics. We start with an introduction to mental health disorders, give a background to genetics and the technologies used to generate genetic data, and then we step through the methods that are used to analyze that genetic data, from quality control, to genome-wide association studies, to polygenic scores, and pathway analysis.

These videos have been collated from online resources, including those produced for the Psychiatric Genomics Consortium, and others from external groups. They range in length from a few minutes, to an hour, and cover both teaching lectures, and methods tutorials. Some videos are marked as "Basic", "Intermediate", or "Advanced", so you can plan your learning program accordingly.

You can use the textbook in any way you choose, working systematically through each section, or picking specific topics that you want training in. *If you identify areas that we don't cover, or that you want to suggest additional videos for, please let us know!* The textbook is a *flexible resource* that we hope to update regularly.

Finally, a huge thank you to the team, who have given their time, their energy, and their enthusiasm to create the textbook. This is an international team from the US, Europe, and New Zealand, and it's been a great pleasure to work together.

We hope that this Psychiatric Genomics Consortium Video Training Textbook fills a need in building capacity in the psychiatric genetics community, and so, enables us to train a new generation of researchers worldwide. With the rapid expansion of available genetic data, the need for skilled analysts has never been greater! And that is an essential step, if we are to realize the potential of using genetics to improve the prevention, diagnosis, and treatment of mental health disorders. And I hope the Video Training Textbook helps you achieve that aim.

------------------------------------------------------------------------

# The Video Textbook Team

Anna Docherty

Howard Edenberg

Lachlan Gilchrist

Laura M. Huckins

**Jessica Johnson MPH**: Data Scientist, Department of Psychiatry, University of North Carolina at Chapel Hill, Chapel Hill, NC, USA

Michelle Kamp

**Hannah Kennedy PhD**: PostDoctoral Researcher, Department of Psychological Medicine, University of Otago, Christchurch, New Zealand

**Ada P. Kępińska PhD**: PostDoctoral Researcher, Departments of Psychiatry and Genetics and Genomic Sciences, The Seaver Autism Center for Research and Treatment, Icahn School of Medicine at Mount Sinai, New York, NY, USA

Cathryn Lewis

Chris Lo

Grace D. Lutter

Adam Maihofer

Caroline Nievergelt

Oliver Pain

Carina Seah

Kayla Townsley

Tim Van Der Es

Jiayi Xu

------------------------------------------------------------------------

# About the Psychiatric Genomics Consortium
