---
title: "Chapter 1.3: History (Video Transcript)"
---

# ***History of Psychiatric Genetics: Part 1*** {#sec-part1}

**Ken Kendler**:

*Introduction*

I'm pleased to be able to talk to you about the history of psychiatric genetics. In this short seminar, all I can really expect to do is to provide a brief introduction and a few highlights. I've decided to focus on the earlier history of psychiatric genetics, as this is likely less familiar to most of you, and rather than only giving lots of dry facts and dates, to try to illustrate this with particular prominent individuals, to provide when I can photos of them, to let you see what their books or articles look like. I would say that the goal I've set myself to show you bits and pieces of the rich history of our discipline of psychiatric genetics so that I might whet your appetite for further self-study.

*Robert Burton*

So let's get started. In a really prequel stage the modern discipline of psychiatric genetics as we understand it started very close to the time of psychiatry itself, that is somewhere in the couple of decades between 1780 and 1800. But we do have one giant figure, Robert Burton, who was writing in the early 17th century, in this case at the date of 1621, a little more than a decade after the death of William Shakespeare, and he wrote what was a classic that has been read up until this century on depression. The title is the "Anatomy of Melancholy", and I want to point to you to a small part where he describes the synopsis of his first partition. As you can see my pointer here, that he describes all the causes of melancholy, dividing them into supernatural or natural, and in secondary as primary he describes about the stars and chiromancy, but here particularly he notes that old age is a risk factor for melancholia temperament, and here we note "parents", it being an hereditary disease. So we have an observation from decades, and actually more than centuries before modern medicine developed and psychiatry developed, with the understanding as people had observed that one form of psychiatric illness, melancholia, clearly passed from parents to their children.

This is a pre-print of an article that is coming out of the American Journal of Psychiatry, and it reflects a rather detailed review of the pre-history of psychiatric genetics from these years of 1780 to 1910. What I next want to do is just highlight this overview. As you can see from the abstract here, I reviewed 48 representative text published during this time period, nearly all of those textbooks had sections on the etiology of mental illness or actually they more frequently called it insanity. In that section they almost always made some comments about the importance of genetics in the etiology of insanity. So here is a review of the main points of that review itself:

**First**, since the beginning of psychiatry as a medical discipline, roughly around 1780, most expert authors who were textbook writers viewed heredity as among the strongest risk factors for insanity. **Second**, during this time period most writers concluded that it was a predisposition to illness, rather than the illness itself, which was transmitted in families. **Third**, and this is related to the concept of predisposition, they were well aware of the apparent probabilistic nature of the transmission of insanity. They noted that it often skipped generations, with an affected parent or aunt a grandparent or aunt or uncle, but the parent as well and the child is affected, and also noted that it seemed to often impact only on a few of many individuals within the same siblings. **Fourth**, authors discussed at length the question of whether there was what they described as "homogeneity" or "heterogeneity" of the familial transmission of the various forms of insanity. The general conclusion was that heterogeneous transmission was the rule. That is, that in the relatives of the insane patients, almost all who would have been hospitalized in asylums at this time. The clinicians who were writing this material viewed a wide variety of psychiatric, and sometimes neurologic, disorders. Homogeneous transmission, that is the idea of like begets like, was an exception. It's interesting that two kinds of syndromes are mentioned repeatedly across these textbooks as being homogeneously transmitted, as one is much of what we would call cyclic psychosis or manic depressive illness, and the other was suicide, with a number of authors noting suicides running in families with high levels of homogeneity. **Fifth**, many writers noted that odd and eccentric personality features were common in the relatives, and especially parents, of their insane patients, and this obviously is a prequel to later developments of schizophrenia spectrum conditions within our own time period. **Finally**, inheritance as they used it, and as Burton used it, was commonly understood more broadly than we would today. It includes prior environmental parental experiences, that is the inheritance of acquired characteristics was accepted for most of the 19th century and even well into the early decades of the 20th century, but also some authors noted that parent-offspring transmission could arise from psychological effects of the behavior of the parents or intrauterine effects.

*Prosper Lucas*

Now, let me turn to viewing a highlight of a series of important authors that we might wish to describe and i want to begin with Prosper Lucas. Prosper Lucas was a French Alienist and geneticist. He lived from 1808 to 1885. He wrote a major two-volume monograph on genetics in 1847, as you can see this "philosophical and roughly physiological traits of natural heredity" would be the translation. These are very long and extensive. It would have one of the great mid 19th century reviews of the field of genetics, and he reviewed them across medical, physical (that would be anthropometric traits), and psychiatric conditions. In addition, Prosper Lucas was in his day what we might call a statistical geneticist and developed a pre-Mendelian theory trying to explain the stochastic nature of inheritance. The importance of Prosper Lucas' work is best illustrated in one of the great books in all of the history of science, Charles Darwin's "Origin of Species", in 1859. He noted Prosper Lucas' book as quote, "the fullest and best on the subject", and in his later works, particularly on "Variations in Plants and Animals", Darwin frequently cited Lucas' work more than a dozen times in that book itself.

*Jenny Koller*

Now let's skip a number of generations to the figure of Jenny Koller, the most prominent woman who contributed to this literature in the 19th century. A bit of background is in order. Throughout the entire 19th century, virtually all observations in psychiatric genetics were uncontrolled. The vast majority of statistics that were reported is a very simple one: that is the proportion of hospitalized psychiatric patients who were hereditarily burdened, and by which they mean has some well-documented history of psychiatric illness or occasionally neurological illnesses in their relatives. These percentages varied very widely from four or five percent to 80 percent, and that's partly because what disorders they consider to constitute a hereditary burden was quite variable and which relatives they counted was also quite variable, but they had never used controls. The first study to do that was done by Jenny Koller in 1895. Here's a picture of what Dr. Koller looked like. She was encouraged by her mother to consider medicine. She met with one of the few physicians in Switzerland at the time, she completed medical school there, but she was unable to get what would be the equivalent of an internship, as they were not offered for women in Switzerland, and so went to Paris, France for her training.

Here is what her article looks like; this would be a translation. She was at that point working in Zurich. I'll give a brief biography in a minute. The title is "Contribution of hereditary heredity statistics of the mentally ill in the canton of Zurich: comparison of the mentally ill with a hereditary burden on healthy people due to mental disorders and such like". We can see that people wrote longer titles in those days for articles than we do today, and this was a relatively prominent journal based in Berlin actually, even though she was Swiss. We published in Neuropsychiatric Genetics earlier this year; Astrid Klee, who's a professional German translator, and I a detailed review of this article, and in the appendix we present an entire translation into English. I want to just briefly summarize for you here just picking up on the abstract.

The first such study in the history of psychiatric genetics that is was published in 1895 that was the doctoral dissertation of a Swiss physician Jenny Koller. She was working under Auguste Forel at the Burghölzi hospital in Zurich, Switzerland, a hospital very famous in the history of psychiatry, and Forel was succeeded by Eugen Bleuler, who we will discuss later. She obtained histories of a range of mental and neurologic disorders in the parents, aunts, uncles, grandparents, and siblings of 370 hospitalized psychiatric patients and 370 controls who were not hospitalized. Interestingly, the rates of hereditary burden were only modestly higher in cases than controls. There was a great deal of surprise at the high level of mental illness occurring in the relatives of unaffected control subjects. However, Koller followed up trying to address two quite important questions: first, she examined which individual syndromes were actually more common in the relatives of the psychiatric patients and the controls, and she found only two categories, which what we roughly translate as major mental illnesses and roughly translate as eccentricities, that is abnormal behaviors, but she also considered syndromes of apoplexy, that is a stroke, nervous disorders, which included such things as headaches, and probably some other neurologic disorders, as well as anxiety and dementia and those three were not more common in the relatives of the psychiatric patients than the controls. Furthermore, the rates of mental illness and eccentricities were much more strongly elevated in the first degree relatives of parents, largely children, largely parents, and siblings in cases versus controls but the elevation for grandparents and aunts and uncles were much less. Again, this was the first systematic observations of the tendency of disorders to aggregate more in what we would now understand to be individuals more closely genetically related. In my view, Koller's study represents a major methodological advance in psychiatric genetics, helping to define which disorders co-aggregated with major mental illness.

*Ernst Rüdin*

Let me now turn to what will be a darker part of the history of psychiatric genetics. This is the figure Ernst Rüdin. I will again give you a brief biography. Those of you who can see will notice that he had a little lapel pin in it with the swastika and that will be part of our story.

Well, Ernst Rüdin was born in 1874, died in 1952. He was Swiss. He graduated from medical school in Zurich in 1898, and his first job was also at the Burghölzi hospital after Jenny Koller to assistant Eugen Bleuler. He then moved to the psychiatric clinic of the university of munich in 1907, where he became an assistant Emil Kraepelin, under whom he completed his doctoral thesis. He was appointed a senior physician there in 1909. When Kraepelin's lifelong dream the establishment of the German institute for psychiatric research, the first such multidisciplinary institute in the world for psychiatric illness, was established in Munich in 1917, Kraepelin appointed Rüdin as the head of the Department of Genealogic and Demographic Studies. Most of the leading members of the next generation of psychiatric geneticists, and that includes such figures as Eliot Slater, Eric Stromgren, and others from all across Europe, came to train in the department that that Rüdin had established in the 1920s and early 1930s. Rüdin himself had two major works in psychiatric genetics, although his school, the program that he established had many many more works.

The first was published in 1911 when he was 26 and in this journal and the title was "Methods and goals of family research and psychiatry". It's an extensive article, and outlines a methodologically sophisticated Mendelian-informed research program for psychiatric genetics, but you will notice in there a number of mentions about "volk" eugenic theories about the "volk" and the wellness of the genes of the "volk" himself. His second major work was this and along with his daughter Edith Zerbin-Rüdin, more than two decades ago, I published in Neuropsychiatric Genetics a summary and abstract of this. The title would be "Studies of the inheritance and origin of mental illness to the problem of the inheritance and primary origin of Dementia Praecox".

This was the first large-scale systematic family study ever done of a psychiatric disorder. It included using these newly developed methods of Weinberg to age-correct the sample and to use a proband-wise correction method to get the correct results. The morbid risk that he calculated for narrowly and broadly defined schizophrenia in the sample was 5.4 and 7.7 percent. Those results are quite similar to modern findings; the study that I did in Russ Coleman early in my career found a rate of six percent, so very much in the range that Ernst Rüdin found. He also found other psychoses were common, with a morbid risk of 5.1 percent, lower rates in half siblings. He noted the risk of schizophrenia was significantly increased in parental diagnosis of alcoholism, a history of schizophrenia in second or third degree relatives, and by parental diagnoses of other psychoses. So overall, Rüdin found a familiar relationship between schizophrenia and other psychoses, a substantially lower risk of schizophrenia in parents versus siblings, and a segregation pattern of schizophrenia that was not did not conform with simple Mendelian disorders. Importantly to note, this was not a case-control family study as we might do now, actually the purpose of this study was to see whether segregation patterns consistent with simple Mendelian transmission could be found. Rüdin did note in this monograph that if there were two recessive genes, those at 0.25 squared would equal a recurrence rate of 0.0625, he said that might be consistent with the model.

Now we need to talk about another key feature of Rüdin's career. Rüdin as a teenager developed a strong interest in racial hygiene and was in 1905 among the founders of the German society for racial hygiene. After the rise of the National Socialists, that is the Nazis, in Germany in 1933, as director of the German Institute for Psychiatric Research (he had taken over the position from Kraepelin after his death), Rüdin collaborated extensively with the Nazi government, praised their racial policies, and received substantial funding both from them and later on from the SS. From 1933 onward, he played a major role in the development of the Nazi program of involuntary sterilization of the medically and psychiatrically ill. It is generally agreed that he was not actively involved in the Nazi T4 program, which was the systematic killing of the mentally ill and mentally handicapped, that began in 1939, but the historical documents are quite convincing that he was aware of these efforts and knew of colleagues who were working in them. And he certainly made no attempt to stop or to publicize them. Furthermore, as documented in high quality historical resources that have only been recently available in English, I would particularly recommend this book by Dr. Weiss "The Nazi Symbiosis: Human Genetics and Politics in the Third Reich". It's quite clear that Rüdin played an important role in the scientific legitimization of Nazi racial policies, both within Germany and internationally, and we know historically of course that the acceptance of these policies laid the groundwork for the future horrors of the Holocaust. In light of his activities from 1933 onward, there is a range of opinions in our field about how Rüdin's substantial scientific contributions to the history of psychiatric genetics should be treated. Some have argued that any discussion of his work is inherently immoral, as it inevitably rehabilitates him, and dishonors the memory of those whose suffering he has contributed to. And i respect that tradition personally, although i don't agree with it. Others have argued that his work can and should be studied for two important and complemented reasons: one, he has played an important role in the history of our psychiatric genetics, but second, as a case study of the potential tragic effects of the misuse of our science.

*Eugen Bleuler*

Let me then go on and conclude with this figure Eugen Bleuler. He's probably the best known of all the people that I've spoken about here. This is a a lovely photo of him as a young man. Bleuler is most famous for introducing the term "schizophrenia" to the world in a lecture in Berlin on 24 April 1908. He revised and expanded his schizophrenia concept in his seminal of 1911. This is his great monograph, "Dementia Praecox, or Group of Schizophrenias", and was unfortunately only translated to English in 1950. But in 1917, that is only a few years after the monograph published by Rüdin, Bleuler wrote a very thoughtful critique of Rüdin's family study of Dementia Praecox, and this is the German version of this. And this is now been published in Schizophrenia Bulletin, which represents a detailed review of Bleuler's comment on Rüdin and, like the other works that I've been doing, here in the appendix, along with Astrid Klee, we publish a full English translation of Bleuler's comments.

I want to review here the four key points made by Bleuler, again working at a time very different from our own. First, Bleuler argued that understanding the transmission patterns of schizophrenian families requires definitive knowledge of the boundaries of the phenotype. And he argues that those remain unknown. Bleuler strongly suggest that Rüdin's choice, which was Kraepelin's concept of dementia praecox, was far too narrow. As we know, Bleuler was interested in such broader concepts as latent schizophrenia. What Bleuler argued was that clarifying the genetics of schizophrenia is inextricably bound up with the problem of defining the phenotype: you can't do one without the other. Second, Bleuler argued for the importance of "erbschizose", which might be described literally as "inherited schizoidia". And he wondered whether either his famous "4 As" or other (and i quote here from our translation) "brain-anatomical, chemical, or neurologic characteristics" might underlie the genetic transmission of schizophrenia. This really is very similar to our concept of what might be an endophenotype. Third, Bleuler was quite interested in the nature of the onset of schizophrenia, suggesting that environmental adversities would often provoke quote "latent" illness to become manifest. It was important to argue that to identify such risk factors and actually incorporate them into the genetic models, a relatively advanced concept we're still struggling with today. Fourth, although not optimistic that current knowledge would permit a resolution of the transmission models for schizophrenia, Bleuler finds single locus models for schizophrenia Dementia Praecox to be implausible, and at several points wonders whether polygenic models (he didn't give the number it certainly was not conceived as the way Ronald Fisher would be), but a small number of genes might better apply.

*Summary*

So this concludes the main part and I want to summarize. My goal has been to introduce you to a few of the many important figures and topics in the history of psychiatric genetics. I want to leave you with one ethical and two overarching scientific themes of this history. The ethical part: our history illustrates the misuses to which the science of psychiatric and behavioral genetics can be put, with tragic results, and therefore the need for our vigilance to reduce the chances of such developments in the future. From a more scientific perspective, I would suggest that the history of psychiatric genetics includes many themes, but two of which are overarching: the first is the close interrelationship between psychiatric diagnosis and genetics. How can you do the genetics of a disorder whose diagnostic boundaries are unclear? So inevitably there is an intimate relationship with these two fields, that is, to get the genetics right we need to get the diagnosis right, and the genetic strategy is one of the best ways to help us decide that what a valid diagnosis is. So we are in this large, long, iterative process. And the second key issue that runs through much of the 19th and early 20th century, is do psychiatric disorders run true in families or is there often heterogeneous transmission? And i would suggest to those of you acting working in the field is that both of these issues are very extant and we have solved neither of them. Thank you for your attention.

# ***History of Psychiatric Genetics: Part 2*** {#sec-part2}

**Ken Kendler**:

My name is Kenneth Kendler. Last year, I gave a presentation on the history of psychiatric genetics that focused on specific episodes and individuals important in the history of our field. Today, I'm going to give a deeper dive into a single episode. The title, as you can see, is "The Beginnings of the Debate Between the Mendelians and the Biometricians in Psychiatric Genetics." I'll be focusing on four individuals: David Herron, Carl Pearson, Abraham Rosenoff, and Charles Davenport. I will be covering a fairly short time period of the years 1913 to 1914, so think of the year just leading up to the First World War.

Now, it's not often that psychiatric genetics work gets into the New York Times, but here, if you were to open up the magazine section of the Sunday New York Times on November 9th, 1913, you would see this big full-page spread titled "English Expert Attacks American Eugenic Work -- Teachings Are Pronounced Fallacious and Actually Dangerous to Social Welfare" by Dr. David Herron of the Galton Laboratory, London. Dr. Charles Davenport makes a vigorous reply. Here's a portrait of Charles Davenport, whom we will get to know somewhat better, and these are two buildings: that was the Eugenics Record Office at the Cold Spring Harbor Laboratory, which has developed into a molecular powerhouse in more recent years.

I want to introduce you to the four key characters: Aaron Rosenoff, a Jewish Emma Gray trained in medicine and psychiatry in the United States; we will be tracking his career in some detail later in the talk. Charles Davenport was a major American Mendelian in the early 20th century; he was at this point the director of the Eugenics Lab at the Cold Spring Harbor. There's a great deal of literature on Davenport's life. David Herron, much less well-known, was a Scottish-born statistician who trained as a Galton research fellow under Pearson at the Galton Research Labs of National Eugenics at the University of London, and he performed the first-ever quantitative genetic study of insanity in 1907. Carl Pearson, I think, does not need much introduction; he obviously was a major figure in the history of statistics and in these years was directing the Galton Labs at London.

Now, all of the four individuals here were ardent eugenics. There are aspects of eugenics and arguments that played into this. I do not emphasize this in my presentation, but if you read the primary sources, you will hear more about that here. Now, what do these folks look like? This is a portrait of A.J. Rosenoff, not the best, but you can get an image of him. This is a picture of Charles Davenport, quite clear, and you saw a portrait of him in the New York Times as well. Um, here is, I could not find a picture, despite much effort, for David Herron, so I give you his first monograph - historically, a quite important document that I may cover in a future lecture. Our first study of the statistics of insanity and the inheritance of the insane diathesis, which was a quantitative study using Pearson's tetrachoric correlation of insanity. And finally, a Carl Pearson, uh, here he is with his family, the son Egan, he will hear more of, and his daughter - I think a very nice mother of Pearson.

So, let's give a little bit of historical background to, uh, what is going on at this time period. After the rediscovery of Mendel's Laws in 1900, an intense and often personal debate ensued about the relevant values of biometrical genetics and Mendelian genetics as applied to plants, animals, and especially humans. As the traditional histories tell us, this debate was largely an English affair centered on two chief protagonists: it was Gregory Bateson on the Mendelian side and Carl Pearson as the lead biometrician. For those of you not familiar with these terms, the biometricians emphasize quantitative traits and thought that you should study relationships among relatives by calculating correlations, especially Pearson's both product-moment and tetrachoric correlations. On the other hand, the Mendelians emphasized investigation of discontinuous traits and were interested in Mendelian patterns of those traits. Um, in essence, what we are seeing now is a small American skirmish as a part of this much broader controversy between these two fields, and here I will give you a bibliography at the end, but these are probably the two best reports about this overall background argument if you wish to follow them up further.

Now, we really get started here with this monograph. This monograph sort of lifts the fire that exploded in the controversy that we saw in the New York Times. Notice the dates of publication. This was initially printed in the American Journal of Psychiatry in 1911 and reprinted in the Eugenics Office. The key author there was A.J. Rosenoff. The title: "A Study of Heredity of Insanity in the Light of Mendelian Theory." This was the first major pedigree study of psychiatric illness ever done, applying Mendelian rules. Uh, it was a couple of years ahead of Ruden's key publication in 1916.

A little bit of background: with a supportive Davenport and his team of field workers from the Eugenics Record Office at Cold Spring Harbor, Rosenoff studied 72 pedigrees who were ascertained through psychotic patients admitted to King's Park State Hospital in New York, which, in fact, is where Rosenhoff was working. They studied, quote, "insanity and Allied neuropathic conditions," unquote, which he claimed in this publication was inherited as a Mendelian autosomal recessive trait. And of course, by that, we mean fully penetrant models of incomplete penetrants were not being seriously considered at this time.

Now, Rosenoff did not attempt to uncover the mode of transmission of specific psychiatric disorders, those, as so, this deviated certainly from the Galton School that looked especially at dementia praecox and certain forms of insanity, and many of the other subsequent genetic investigations we are used to. Rather, he focused on a very broad phenotype that he termed the neuropathic constitution.

And what he tested: the Mendelian model by examining segregation rates and relationships from these pedigrees as a function of their mating type. He studied 206 matings with a total of 1097 offspring, and any well parent with a neuropathic offspring was assumed to have a heterozygote genotype. So, just so you're familiar, with these, D stands for the wild type, and R is the risk allele. So, a Dr is a heterozygote, and he focused on six mating types, and you can read these out, of course. These are going to be given the recessive model that he assumed: affected by affected, affected by a heterozygote, affected by a wild homozygote, heterozygote by heterozygote, wild by heterozygote, and wild by wild. And from simple algebra understanding Mendelian predictions, you have these percentages expected in the offspring of those individual mating types from zero percent to one hundred percent.

Now, what's the phenotype that Rosenoff studied, and this is obviously a little bit from the monograph itself. In studying any neuropathic defect, one must bear in mind that its clinical manifestations will vary with the personality of the subject and the conditions of the environment. It is indeed a notorious fact that most of the so-called clinical entities are remarkable for the variety of their manifestations. This fact has necessitated the introduction and clinical practice of the conception of neuropathic equivalence, and that will be a major topic that we will discuss further. Now, this is the key result from that monograph that I'll go through, but I redo this in a clearer format. But, in effect, these are the mating types with the B and B1 differing about whether you know that the person is a heterozygote because they have an affected offspring. We affect the assumption of their model and one in which you assume that, but you can actually read off the EXP versus The observed, and in the next figure, you'll be able to see that more clearly. So, if you scan your eyes down these columns, you'll note that there's a fairly significant deviation here but for most of the other columns and somewhat there, there's moderately good agreement between.

Now, there was no chi-square test, even though that had been invented a number of years ago, no statistics observed, but from these pedigrees, Rosenoff and Reach the following conclusion, as is shown in the table: the correspondence between theoretical expectation and actual findings is in some cases exact and in all cases remarkably close. It would seem, then, that the fact of the hereditary transmission of the neuropathic constitution as a recessive trait in accordance with the Mendelian theory, may be regarded as definitively established.

Let's look at some of the pedigrees; they are all presented in the monograph, and I'm only going to give you a selection, but just to get a clue about what the meanings of the symbols are. So, the clear squares and circles are going to be normal progeny. Those with a little circle in them are a normal subject without progeny, and so they can't, according to their system, no other person is a normal homozygote or a heterozygote. And then these are normal subjects with neuropathic progeny, which, by their definition, have to be heterozygotes. And then the affecteds who need to be homozygotes are the fully shaded ones, and then the ones about dieting child another again, you can study this at your leisure if you so wish.

So, I'm only going to show, I think, four pedigrees, but working through those, although maybe a little tedious, will be helpful to get a sense of the data. So we always have the proband who is hospitalized at King's Hospital in this pedigree. In this case, we have a manic-depressive insanity case hospitalized, then all the affected---let's go through those first.

This woman has a sister who is described as very nervous, which meets their criteria, or theirs, for a neuropathic trait. She has a mother with epilepsy, a maternal grandfather with epilepsy, and a paternal grandmother who is described as "hysterical when a girl had ideas someone was trying to poison her." The only other people here are the obligatory heterozygotes by Rosenoff's system, and again, because they had affected offspring, assuming their recessive inheritance, those are obligatory heterozygotes. So that's the first pedigree.

Second pedigree, here again, we number seven as the proband with manic-depressive illness, and this is, again, a heterozygote by ill individuals. So according to Mendelian theories, these should, on average, have 50% affected. We have, with this affected male proband, a sister who is described as "easily excited in a nervous temperament," which is assumed to be neuropathic. She has an affected father with recurrent melancholia with insomnia, having spent five months in a sanatorium. She has a paternal uncle who is described as a "crank," and a maternal aunt described as having convulsions, and a maternal uncle described as convulsions. Note that these also both meet criteria for neuropathic trait and are considered affected. And then an affected paternal grandfather with senile deterioration, presumably due to some kind of dementing illness like Alzheimer's.

Okay, third pedigree, this is obviously now four generations, so much richer. We have the core sib ship here, and here we have, it looks like a double proband family, so both nine and ten, which is our recurrent melancholia with suicide attempts and manic-depressive insanity. The sister and brother, and they have one affected sister who is described as "attack of depression with suicidal tendencies." This is a homozygote by homozygous mating, with the father having had fainting spells, and the mother having been diagnosed with recurrent attacks of depression. There's a paternal grandfather who is described as "money mad, very cruel, very miserly, wealthy, left much of his money to a housekeeper." And then we have a maternal great-grandfather who's described as alcoholic. We have a couple of individuals here who are marked as heterozygotes because of their obligatory office, by, because they had offspring.

So, number four had a daughter with fainting spells, not drawn on the pedigree, but the authors are willing to assume that she must be a heterozygote because of that. And this uncle had a feeble-minded and "queer" son, and again is assigned as an obligatory heterozygote. And then these parents, because they were intervening between these, must have been heteros to transmit the recessive trait.

And this is the last and obviously a much broader pedigree. So here we have a very rich, dense pedigree in which number 13 is a woman who is the proband with dementia praecox. She has two affected older brothers, who are alcoholic, actually both of them affected. Younger brother with a highly nervous temperament, worries, and also with alcoholism, and number 11 worries over things. His sister with blue spells. The father is described as neuropathic with a highly nervous temperament and irritable. One of the uncles is a nervous temperament, alcoholic. Another uncle highly nervous. And then a sister who has a daughter who's nervous, so she is considered to be an obligatory heterozygote. And then we have a very dense pedigree here in the metro line: fainting spells, shiftless, alcoholic, spending sprees, religious crank, alcoholic, and inferior make, a possibly epileptic, and then an affected maternal grandfather: alcoholic, cranky story.

So those are examples of the pedigrees that Rosenoff uses to reach the conclusions that this neuropathic trait, which they consider to be indicative of insanity or vulnerability to insanity, is indeed inherited as an autosomal recessive. So the next step is that in 1913, so about two years later, but there must have been some publication lag, David Herron and Carl Pearson write a three-part series of monographs entitled "Mentalism in the Problem of Mental Defect." They didn't mean this to include both what they would have called mental handicap and psychiatric illness, but Herron is the lead one, and the title of this is a "Criticism of Recent American Horror."

And this is the monograph that directly prompted the New York Times article. And we will, um, I'm going to just read this briefly, and again, if you want to stop the video and read it in more detail, but this is now from that front-page article. I'll just give you a quote of what I think was written by the reporters in the New York Times: "A spirited attack has been made by Dr. David Herron of the Galton Laboratory, University College London, upon the entire body of American eugenics in general and the work of the Eugenics Record Office at Cold Spring Harbor, under the direction of Dr. Charles B. Davenport, in particular. The criticism, which finds the work of the American investigator biased, faulty, and exceedingly slip-shod, is issued in the form of a monograph, the essential content of which is published below, together with a reply by that cada Davenport himself". So, Dr. Herron got most of his monograph published in the New York Times, not bad, and you can read the rest as you will.

So let me try to summarize a fairly lengthy, and I'm going to be simplifying a number of issues and not dealing into everything, but I'm trying to touch the high points here. So, what did Heron say about the problems with Davenport's work? And this is both his mental handicap work, which I'm not going through, but on virtually all of it applies to the study of the insane diathesis as well. Quote, "As a defender of the young science of human genetics, which was at this historical stage nearly inseparable from that of eugenics, Heron describes a critical problem of the defenders, which he sees himself and, of course, his mentor, Carl Pearson, of the young field." And now this is a direct quote: "They see, unfortunately, dogma outstripping knowledge. They see fallacious methods of reasoning applied to problems which are essentially statistical by numerous writers who lack the necessary training." So, we will see that we're going to be into some sort of heavy, rather personal descriptions in the ensuing monograph.

Let me try to run through substantively what was Heron critiquing in Rosenoff's work. He begins by focusing on the fieldwork itself, and notice here, many of these also apply and uses examples of Davenport's earlier study of feeble-mindedness. First, Davenport published lots and lots of monographs, and one of them was a field manual for interviewers. Again, he hired this team of mostly young women that would go out, identify pedigrees. We don't know anything about the specifics of the assessments, but they did contact them based on personal contact, and that was an important methodological advance. So, I don't want to play down some of these important advances, and Davenport did track down Huntington's career pedigrees, as well as his work in these other areas. But there are some rather concerning quotations from this field manual for interviews, and this is again a quotation with a highlight from Heron's monograph itself, and again I will read this. "Some defects that the field worker will study," I am quoting Heron's quote of Davenport's monograph from field workers.

So, this is his instructions: "Some field workers will study such defects as albinism and feeble-mindedness, are known as recessive defects." So he's assuming that feeble-mindedness, a pretty broad phenotype, is recessive. For example, by hypothesis, feeble-mindedness is, for the most part, a recessive trait, and the hypothesis must be tested as follows. So he's telling the field workers how do you test for a recessive disorder. "You must find a person suffering from feeble-mindedness who is a descendant of two normal parents (hypothesis: both of the parents are simplex, meaning heterozygous). The field worker must understand that each parent will probably have somewhere in his or her ancestry a feeble-minded person, and it is the business of the field worker to make a special search for such person or persons in the pedigree."

Now, you can see why Heron would cry foul. Heron, now quoting from his monograph, says, quote, "It is difficult to understand how the field workers would fail to be prejudiced by these instructions, which appear to be telling the field workers the pedigree structures they are supposed to find." Heron concludes, quote, "What faith are we to place in data collected in this way when we find that the field workers are instructed to, quote, make a special search, unquote, for those individuals who are necessary for the support of the Mendelian theory, and when the data are, quote, indexed in such a way that no exceptions to Mendelian rules can appear," he is quoting from another version that I didn't want to burden you with, explaining how the field workers had to find pedigrees that don't appear to deviate from the expected Mendelian expectations.

So, pretty hard and well-supported concerns about field workers. Next, he addresses the vagueness of the phenotypes that Davenport and colleagues used, and again, Davenport publishes, quote, "The Trait Book of the Eugenics Record Office," which you can also look up, a 52-page listing of their various phenotypes, and these will test my vocabulary here, but this is just from the eyes and the L's, most of them here. This is quoting from Heron's quote, "These are the phenotypes that they were interested in having their interviewers in fact. Impracticalness, adventurousness, disheartedness, unconversationalness, unacquaintanceness, ludicrousness versus absence of sense of humor, sublimity versus solidity, sweetness versus bitterness, coolness in emergency versus loss of head, cooperativeness versus aloofness," and it goes on for page after page after page. Again, quote, "The use of the term 'insanity' in the titles of these two papers is very misleading."

Parents says only a comparatively small proportion of the affected individuals are actually insane. These papers deal not with the inheritance of insanity but with the inheritance of what the authors call a neuropathic condition which is so comprehensive that it is a matter of surprise that there are any normal individuals at all. You notice a touch of sarcasm in his tone. "It is indeed a fortunate circumstance that the Mendelian theory requires the presence of some normal individuals," end quote.

And here again is a quote, bear with me, but I think this is important. "The neuropathic condition is based upon appearances and conditions manifest from infancy to old age, and the following are some of the conditions with the author's opinion justify classification as neuropathic," and they (what Heron does) and the saying that we did is we go through pedigrees, but he went through many more of them, and he obviously is picking out the ones that seem to be particularly unusual. God in infancy of convulsions, senile deterioration, dot of miasmas, Sister of Mercy in Australia said to have died of homesickness, quick-tempered, very in very queer lives alone, bores out cats, restless, fidgety, nervous, cold headache, sick headache, worry or Rambler, neurality, insomnia, dictatorial, selfish, not very bright, high-strung, odd, very quiet disposition, lost interest in life, etc.

Now, I did my own research here. I picked by random 10 of Rosenoff's pedigrees, and they had 73 affected individuals in those 10 pedigrees. And I classify them using their own description: 21 - their main definition was nervous, 13 were described as eccentric or clear, seven alcoholic, six high-strung, four cases of dementia praecox (which the law were probands), four cases of manic-depressive insanity (all probands), four imbecile or feeble-minded (so those were probands), and one is microcephalic. So, I think Karen is right that in the description, the vast majority of individuals in these pedigrees are not severely mentally ill individuals, so terming this the genetics of insanity can be questioned.

Then Heron turns, and this is the hardcore statistical part of the argument, to two ascertainment problems. Davenport and Rosenoff never correct for the proband through which they ascertain the pedigrees, thus biasing upward rates of illness in that siblingship. Those of you that are not familiar should be aware that the early efforts to try to see especially for recessive patterns from familial traits that you find families with potential affected individuals, and this was mostly in the five to eight years right after Mendel's work was discovered, kept getting ratios above 25. And it was Weinberg, a pediatrician, a German physician, who noted that you cannot count the affected individual. He developed what is his so-called program correction method, which, by the way, Luden adopts in his methods. But it does appear that neither Rosenoff nor Davenport were aware of this and the fact that counting the affected person, as they always do in the ratios, is going to bias upward in a substantial way. So that's problem one.

Second, they don't correct for the fact that larger siblingships have many more affected and are likely to be ascertained. And that, we, in fact, one of the pedigrees we saw was doubly ascertained, and they didn't correct those. They have to be counted independently, which again Weinberg points out to get the correct findings.

Now, interestingly, Heron doesn't raise the problem that they don't correct for age so that an individual who is unaffected and 25 years old, unaffected and 50 years old, probably should be kind of different. By any criteria, you will find that if you're trying to get Mendelian segregation ratios for age-dependent penetrant phenomena, you're not doing correct for age, you're going to distort things. But Heron was not apparently aware of that, although Weinberg was.

So here, in summary, we believe that those who dispassionately consider the papers discussed in this criticism must conclude, with the present writer, that the material has been collected in an unsatisfactory manner, that the data have been tabled in a most slipshod fashion, and that the Mendelian conclusions drawn have no justification whatsoever. And when we find such teachings based on the flimsiest of theories and on the most superficial of inquiries, and noticing the rather ad hominem attacks here proclaimed in the name of eugenics and spoken of as entirely splendid work, we feel it is not possible to use criticism too harsh, in our words too strong, in repudiation of advice which, if adopted, must mean the death of eugenics, think also human genetics as a science. Okay, so that is Heron's response.

Now, I'm going to go through much more briefly the comments of Carl Pearson, who wrote the other two monographs. Pearson was far more diplomatic in his comments. Um, I'm only going to point out two things. One, he notes that especially the mental defect sections that really treating this as a dichotomy is probably not reasonable and that it's better understood as a continuous trait. In fact, Pearson and the Galton lab did a number of correlational-based studies of estimates of intelligence and mental handicap. And then, he also expresses concern about the phenotypical assessments and, as we saw, the assumption which got counted in there of heterozygote status without evidence. That is the circular reasoning of counting the heterozygous implicatorially, which assumes the transmission pattern you're trying to test.

Now, let's get into Davenport's response. This is, in fact, from The New York Times directly, and then we'll get into the monograph, but I think we can begin to get the tone of how Davenport responded here, quote, "A sweeping condemnation of American work in the science of eugenics is issued by the Galton Laboratory of University College under the direction of Dr. Carl Pearson."

The specific criticism of American methods and American findings being presented by Dr. David Herron, note the nationalism implied here, this condemnation which finds the contribution of America based on worthless, slipshod research and filled with unwarranted conclusions is based chiefly on the Eugenics Record Office bulletins. Being myself responsible for the work of the Eugenics Record Office, which includes not only the actual laboratory work done at Cold Spring Harbor during the past three years, but the active collaboration of institutions and individual scientists throughout the country, think Rosenov, I feel like it is my task to explode the false and injurious impressions sure to be created in the popular mind by the broadcast criticism issued from the Galton Laboratories. So, again, pretty directly attacked.

Now, let's switch to a couple of months later. So Davenport didn't really rest on his hunches here. He published a brief one-page response in Science magazine, which again you can read either here's the reference here, but I am going to jump to some quotes from this.

You can, again, see the general spirit of the vocabulary, and this is how he begins it: "The all-too-familiar blessings of Professor Carl Pearson about Mendelians have recently been continued by this understudy, Dr. David Herron, and directed toward American work in general and that of the undersigned in particular. Like my colleagues in this country, I should have remained silent under the attacks, knowing that discriminating men of science in this country, as well as in England, recognize their true animus that they lie outside the pale of science."

And then a couple of other quotes from that short Science article: "The numerous errors to which he calls attention fall, for the most part, into three categories based on misunderstandings so gross of the critics, on the critics' part, as to render it difficult to believe they are not intentional. A critic who is guilty of such extensive, stupid, captious, and misleading criticism can hardly expect a scientific consideration of other points he raises." So pretty strong language. It will be futile, as a biologist, to attempt to show to the applied statistician his errors.

So, noting the contrast, biology, good, positive. We're going to get to the biological root. Statisticians just deal with numbers, not real biological facts. Quote, "Genuine scientific criticism has always been useful in the advancement of science, but friends of Galton must regard it as a tragedy that the fortune of one of the largest-minded and most fertile men of science," (small digression: Davenport liked Galton a lot, and in fact, Galton was surprisingly ambivalent in this Mendelian-Biometrician controversy, kind of switching from one side to the other because he liked some of the concepts of Mendelians) "so he, Davenport, is praising Galton and derogatory toward his main pupil and mentee, Carl Pearson. So Galton should be supporting a laboratory one of whose leading members (think Pearson) spends much time making elaborate researchers into his delusions concerning the blunder of others, instead of making positive discoveries in a field where so little is known and where the need for utilizable knowledge is so great."

Okay, so now let's go to the last article I'm going to consider in detail, which is Rosenov's response. Rosenov wrote a longer article in 1914, so again, moving pretty quickly given publication lag, and the American Journal of Insanity that in 1921 changed its name to the American Journal of Psychiatry that many of us know well. So here are some selective quotes:

"In reading Dr. Herron's pamphlet," this is now Rosenov speaking, "what is struck, first of all, by the unusual temper of the attacks, apparent on almost every page. The work of Davenport, Toomey, Goddard, who worked mostly on mental handicap, and some others are analyzed in a fashion are referred to without a single feature being found in them to be worthy of anything but unreserved condemnation from the critic." He quickly, however, and I think this is the most interesting part, gets to see what he sees as the heart of the dispute.

Now, I find it intriguing that it is Rosenoff, the psychiatrist, and not Davenport, the real-deal geneticist, who makes these points. The unfortunate position in relation to the scientific world of the English biometrical school, to which Dr. Herron belongs, may account in some measure for the temper of the attack. They have, by reason of a pride in their own tradition, that think correlations refuse the guidance of the light of mentalism, continuing to devote their time and labor to the investigation of the heredity of various traits in man, as well as in plants and animals, by purely statistical methods (note that's not used in a praiseworthy manner). While biologists, note the contrast, all over the world, were piling up evidence of observation, experiment, continuously adding to the support of Mendel's theory, eventually, it came about that the work of the Galton Laboratory has been valued by the scientific world for the development of refined statistical methods and not as a biological contribution to the subject of heredity. So, Rosenoff really kind of calls it as he sees it, that is, the statistics versus biology controversy that I think, in many ways, fed this scientific and eventually personal controversy.

He goes on. Rosenoff then quotes Bateson, who, up until now, we haven't heard his name, but in the English world, he is the leading member of the Mendelian group, very vigorously against Pearson but not about psychiatric illness. By March, and we're now quoting from Bateson, "Of the so-called investigations of heredity by extension pursued by extensions of Galton's non-analytic method and promoted by Professor Pearson and the English biometrical school, it is now scarcely necessary to speak. That such work may ultimately contribute to the development of statistical theory cannot be denied. But, as applied to the problems of heredity, the efforts have resulted only in the concealment of that order which it was ostensibly undertaken to reveal." In other words, statistical methods will never get to the true genetic factors; only the Mendelian approaches will be successful.

Final criticism, which focused on Heron's lack of clinical training, suggesting that is a universal agreement. We'll see. So this is it. It was the last. Rosenoff: "The burden of proof is upon the critic who, though a layman, assumes an attitude in relation to his psychiatric issue diagnosis which is in opposition to a view universally held by psychiatrists." That's simply factually incorrect. In fact, most workers in the field at this point would have focused more on the genetic transmission of specific disorders, although some others did emphasize these very broad kinds of diathesis. So coming back to the quote, "And if he furthermore attempts to disqualify on the basis of his attitude work which, in his opinion, contains too large a margin of error, he must, in addition, take the burden of furnishing an acceptable measure of the error before his criticisms can be rendered valid. This our critic has not done." She was basically saying he's got no business criticizing my psychiatric judgment about the breadth of these phenotypes that he studied.

All right, so let me now summarize what I've taken you through. I've left out a lot of detail, but I think I've touched the high points. So first, it's pretty obvious there's a high level of acrimony, harsh, rather derogatory language on both parties. We've got a mixture of some substantive scientific critiques, but quite a lot of ad hominem attacks, not the best way to do science, I have to say. This is certainly started by Heron, but Davenport and to some extent Bateson give it back in measure, and Rosenoff, you know, still has, uh, takes his gloves off to some extent.

There are a couple of articles in the reference, one particular contemporary commentator who praises Heron's science but castigates Heron for this derogatory approach. But it's very interesting, I found an obituary of Heron written by Egon Pearson, that was the little curly-headed kid at the left of the Pearson picture, and he wrote, quote: "Recently when I asked Karen how he felt looking back about these years, and I think in his academic career, this controversy was pretty substantial, he replied to the effect that as a young man he enjoyed a good fight." So I think we'd get the response from Heron as an older person that he obviously enjoyed some of the more pugilistic intellectual combat that he engaged in, and yeah, it got started with his monograph.

I think, having studied this a fair bit, that there's quite substantial evidence that Davenport used biased field methods, and this is true across a number of the monographs. So, I think there is circular reasoning in the way he trained field workers, training field workers to go out, especially, and find the pedigrees that validated their mendelian assumptions.

I think that the phenotypes used and the associated assessment methods simply strain credulity. I don't have time to present you, and this is a trend of Davenport. Davenport wrote his most notorious monograph, which is called "Nomadism or the Wandering Impulse," in which he determined was a sex-linked recessive with affected individuals. And this is again, I read from this pedigree table, having phenotypes including Western Desperado, sailor, traveling salesman, itinerate Tinker, canal boat captain, as manifesting this sex-linked recessive trait called nomadism.

And again, although this is not pointed out in this debate, several other psychiatrists, including Abraham Myerson, an important figure in psychiatric genetics during this time period in America, also strongly disagreed with Rosenoff's very extended diagnostic pattern, saying these are completely impossible. So, Heron was not the only one challenging this.

There are methodologic errors for Davenport and Rosenoff that are really quite clear-cut, that is, their simple failure to correct for ascertainment biases. This has been published in German by Weinberg a few years before. What can explain that given that Davenport, certainly his reputation, was based on studying human pedigrees, so he was not at that point on the cutting edge of the algebraic problems of how you get mendelian ratios, and one has to fall to them, and again, that no age correction was performed. And here we see the much greater methodologic sophistication of the Louden School compared to what Davenport was doing. So if I had to judge (but you can all reach your independent opinions), Heron is considerably more right than wrong in his critique of Davenport and Rosenoff, and history, by and large, supports this judgment about the validity of the scientific work and particularly the claim of a clear demonstration of autosomal recessive inheritance of this so-called diathus that they study.

Now, I don't think this forgives Heron's tone, but it is a hard for modern readers not to share some skepticism of these methods. To take a step back, what led David Port and Rosenoff to these misjudgments? My own view is that this was a case of what you might call mendelian zealotry and over enthusiasm for mendelian models that can distort scientific judgment. But again, you should reach your own conclusion. Does this have implications for the subsequent history of psychiatric genetics? Well, I think it does. For example, in the late 1980s, this all followed the 1983 demonstration of Huntington's chorea by Jim Guzella using RFLPs. There was a rush of interest and enthusiasm of linkage jobs for psychiatric disorders, and these, of course, depend on mendelian, or, you know, we call single major locus models of large effect mendelian-like transmission.

Some of us in the field (a lot's participated, myself included) talked about the methodologic difficulties, the fact that we don't have evidence from Indian-like segregating pedigrees for these, that we ought to be worried about false positives, and we certainly shouldn't be studying very small numbers of pedigrees. Those of you old enough to know, there were three very high-profile false report results of mendelian segregation using linkage analysis for manic depressive illness in 1987 and one for schizophrenia in 1988, and these are the three of them: Baron et al., Sherrington et al., and Janice Egeland, all very high-profile and very disturbing to the field. Gradually, the non-replications came in.

So, in my view, it is hard to underestimate the strength of the lure of mendelian models for Psychiatry Genetics. Psychiatrists are craving widespread scientific credibility; they want to demonstrate that genetics is appropriate to find a form and a mendelian model is so attractive to them. And this was a time again, in the 1980s and early 1990s, where twin research was also blossoming.

We had the first interview assess population-based studies, both with David Folker at IBG and Linda Neves at VCU. We had wonderful quantitative models fitting these liability threshold models, and I personally experienced tensions between the twin and the molecular researchers, including what you would see at earlier meetings of the World Congress of psychiatric genetics. And if I had to characterize it, if you were listening to each group critical of the other, you had the two following stereotypes: the mendelians, mostly people doing linkage analysis, when they want to put down the Twin researchers, used this phrase, "you're not doing real genetics, you're just looking at statistical models," which of course completely echoes what we saw 60-70 years earlier in the Dilemma that we've seen here between the biometricians and the mendelian. So really, what goes around comes around.

What were the Twin researchers saying of these people doing linkages, sometimes on three, five, or eight pedigrees? Quote, "you're just a star-struck gene jock fitting models that we don't know don't apply." So we have the same kind of ad hominem attacks between these two fields that have visited us again. So the tension between mendelian and biometrical genetics has been on the root of psychiatric genetics for several Generations now. And you would give me a minute to say, I think there's a deep irony in the evidence that has emerged from Gua studies in recent years, that is the Pearson fissure model of a normal distribution of liability due to many genes of small effect has actually turned out to be right.

So, the mendelians were wrong in all their claims that "you're just studying statistics" and the real biological understanding is only going to be through classic mendelian models. And it's very pleasing to see, in some important ways through PRS scores through samgy was, that we are now seeing a bit of a merger of these fields. Have we finally calmed down from this kind of internessing argument that we've had with one another across the generations?

So, before I conclude, what happened to the main players in this little story? Well, Charles Davenport gradually lost influence. He was an ardent eugenicist and was influential in immigration restrictions from Southern and Eastern Europe during the 1920s and 1930s. He retired in 1934. The Carnegie Foundation, which was really supporting all of this, withdrew critical support for the Cold Spring Harbor laboratory in 1940. In part, because the enthusiasm of the Eugenics movement in the United States diminished substantially with the rise of the Nazis in Germany from the mid-1930s on. Davenport did not reduce his enthusiasm for that.

David Herron, on the other hand, left academia in 1915 and worked for an insurance company in England. He went on to be the president of the Royal Statistical Society and had a distinguished career, but he was not doing this kind of work.

Aaron Rosenov went on to a distinguished academic and administrative career in psychiatry. He led the first U.S. twin studies of schizophrenia and expressive illness, so he reverted to more traditional diagnostic-based approaches, and he was sufficiently well-known to be appointed the state Commissioner of Lunacy in California in 1933. He also wrote a textbook, so he did relatively well for himself. Pearson remained the Galton share of eugenics at University College London until his retirement in 1933. He was at that point, although perhaps a little bit eclipsed by Ronald Fisher, one of the giants of statistical work. In June of 2020, UCL announced that it was renaming two buildings which had been named after Pearson because of connection with Eugenics (and for all of these authors you will read parts of here where they are very enthusiastic about eugenic pressures, and that's a whole other talk). Last word in the New York Times, Heron got his last point. So this is now January 4th, so it's like a month later, and you can see Heron accused the head of the American Eugenics record office of callousness, inconsistency, and misinformation, and says that the following of his advice would mean the death of eugenics as a science.

So here is I am writing a paper on this, so this is an extensive bibliography on this page, and last, so again you can freeze your frame if you want to look at these in detail, and this is a rich area for those of you that have historical interests. I appreciate your attention, thank you.
