---
title: "Chapter 4.1: Epidemiological study design (Video Transcript)"
---

**Title**: Epidemiological Studies: A Beginners guide

**Presenter(s)**: Ranil Appuhamy, James Clark, Let's Learn Public Health

\[Music\]

Hello, and welcome to this video on epidemiological studies. We're going to have a quick look at epidemiological studies, what they are, a few different types of studies, their advantages, and disadvantages.

*What is a study?*

First of all, what is a study? Well, simply put, a study is a scientific process of answering a question using data from a population. It can be any question. For example, does smoking cause cancer? Is there more disease in one area compared to another? Or, what food is responsible for causing an outbreak? So, the first thing to do in any study is to have a study question. What are we trying to find out? Then, we need to figure out what the best type of study is that would help us answer the question. Once we've decided on a study type, we need to do the study, collect and analyze the data using a suitable statistical method. Then, we need to interpret the results to make sense of it all, and finally, we need to report the results of our study. Importantly, all studies need to be done in an ethical way. Now, let's have a look at a few different study types.

*ECOLOGICAL STUDY*

An ecological study is the type of study where measurements like disease rates and information about exposures are made on a group of people. The groups can be as small as people in a house or as large as people in an entire country. It's important to remember that results and conclusions from ecological studies apply to a group and not to individuals. Ecological studies are useful for comparing the health of populations in different places, such as measles rates in Australia and New Zealand, or at different times. They're also useful for generating questions and highlighting issues that can lend themselves to future investigations or studies.

*CASE SERIES*

A case series describes the characteristics of a group of people who have the same disease or the same exposure. The aim of this is to understand the demographics, clinical presentation, prognosis, or other characteristics of people who have a particular disease or describe something unusual. For example, in the early 1980s, the occurrence of an unusual pneumonia in men led to the recognition and identification of HIV.

*CROSS-SECTIONAL STUDY*

A cross-sectional study takes a selected population and measures health information at a given point in time, giving a snapshot of their health. It usually involves asking participants a series of questions using a questionnaire. Health surveys that collect health information about people in a population are an example of a cross-sectional study. Because these studies commonly measure how many people have a disease at a particular point in time, they're also called prevalence studies. It's important to make sure that the selected population is representative of the total population.

Cross-sectional studies are relatively inexpensive and easy to conduct compared to other studies. They can provide information on multiple exposures and outcomes and are a good way of assessing the health needs of a population. However, because the information is collected at a single point in time, it cannot be used to determine whether a particular exposure caused the disease or not.

CASE CONTROL STUDY

A case-control study starts off with cases, which are people with a disease. It uses a comparison group called controls who are similar to cases but do not have the disease. Then, both groups are asked about their previous exposures to different risk factors. Now, for each of the risk factors, the odds of being exposed if they were a case is compared to the odds of being exposed if they were a control. This is called an odds ratio. An odds ratio of more than one means that people with the disease are more likely to have been exposed to that risk factor than people without the disease. This suggests that it could be a possible cause of the disease. An odds ratio of less than one suggests that it's a protective factor, and one suggests no association. Case-control studies are commonly used in foodborne outbreak investigations. For example, we can compare the odds of eating different kinds of food between people who fell ill after consuming a meal and those who didn't. If the odds ratio is greater than 1 for a particular type of food, then it's possibly the cause of the illness. A major advantage of a case-control study is that they're often quick and cheap to do. Also, because they start off with cases, they can be used to study uncommon diseases. However, because these studies involve small numbers, they're not good to study rare exposures. One of the challenges in a case-control study is to find suitably matched controls. Also, because studies ask about exposures in the past, people might not be able to recall their exposures accurately.

COHORT STUDY

Let's have a look at cohort studies now. In a cohort study, a group of people is followed over a period of time to see what happens to them, and information about risk factors is collected. We can then compare the occurrence of an outcome like disease in those who are exposed to a particular risk factor to those who are not exposed to that risk factor. The main measurement used in cohort studies is called the relative risk. A relative risk is the ratio between the risk of disease in the exposed group compared to the risk of disease in the unexposed group. A relative risk of greater than 1 means that the exposure is associated with an increased risk of the disease. If it is 1, it indicates that the risk is the same, and if it's less than 1, it indicates that the risk is lower. A well-known cohort study is the British doctor study done in the 1950s, where a group of doctors were followed up for many years. This study provided valuable scientific evidence of the harmful effects of smoking, especially the link between smoking and lung cancer. One of the main advantages of cohort studies is that the time sequence of events can be determined. This is useful when trying to determine what caused a disease. Another advantage is that information about several different outcomes and risk factors can be collected at the same time. This allows for some analysis to be conducted on the data. A disadvantage of cohort studies is the high cost, and they can involve a large number of people being followed over a long period of time. They're generally not suitable to study rare diseases. A challenge in cohort studies, especially ones that are conducted over a long period of time, is ensuring that people who started the study stay until the end of the study. If many people drop out, it will affect the results of the study.

INTERVENTIONAL STUDY

Now, let's look at another type of study, an interventional study. In an interventional study, an intervention is done on a group of people, and the outcome is studied. Examples of interventions can be giving a medicine, a vaccine, or health advice. The outcome can be things like a change in disease status or change in behavior. A randomized controlled study is the best study design for an interventional study. Say we want to study the effects of a new drug. We start off with a study population, and people are then randomly allocated to be in the intervention group where they receive the drug or in the control group where they don't receive the drug. Then, after a suitable time period, the outcomes in the two groups are assessed and compared to see what effect the drug had. Outcomes can be things like a change in disease symptoms or death rates. Ideally, neither the participants nor the investigators should know which group received the intervention. This is called double blinding and ensures that neither of them can influence the outcome of the study. The main advantage of a randomized controlled study is that it can provide good evidence that the intervention led to an outcome. Randomization ensures that both groups have an equal chance of receiving the intervention and that they have similar characteristics. This way, the effect of the intervention can be determined without other factors influencing the outcome. The disadvantages are that these studies.

*SUMMARIES*

Finally, sometimes it's challenging to keep up with all the studies that have been conducted on a particular topic. Fortunately, there are studies that summarize other studies. There are two main ways that this is done: a systematic review and a meta-analysis.

A systematic review systematically identifies all the relevant studies on a particular topic, assesses the quality of each study, synthesizes and interprets the findings, and presents an impartial, unbiased, and balanced summary of the evidence. A meta-analysis, on the other hand, uses data from all the studies that have addressed the same question and have a similar study design. It then combines the data from these studies to perform a statistical analysis and produce a single summary result.

And that's an overview of some of the commonly used epidemiological study types. We've looked at what a study is, different study types, their advantages, and disadvantages.
