---
title: "Chapter 2.2: Genetic Variation (Video Transcript)"
---

The differences in our genes come about through a natural process called mutation. Mutation is extremely common. As a cell copies its DNA before dividing, it makes occasional typos. Most commonly, a single base is substituted for another.Sometimes a base is deleted or an extra base is added. The cell is able to repair most of these typos. But each round of cell division introduces a few changes that are not repaired. When DNA changes occur in cells that will give rise to eggs or sperm, they can be passed down to offspring. Each one of us has about 60 new variations that were not present in our parents.

People commonly use the terms mutant and mutation to describe something undesirable or broken. But mutation is not always bad. Most DNA changes fall in the large areas of the genome that sit between genes and they usually have no affect. When variations occur in areas of the genome that code for proteins, they often have consequences. These changes can effect the protein product itself or they can effect when, where, or how much protein is made.

Most of the time, mutation generates variations that are neither good nor bad, just different. While a mutation is defined as any alteration in the DNA sequence, biologists use the term \"single nucleotide polymorphism\" (SNP) to refer to a single base pair alteration that is common in the population. Specifically, a polymorphism is any genetic location at which at least two different sequences are found, with each  sequence present in at least 1% of the population. Note that the term \"polymorphism\" is generally used to refer to a normal variation, or one that does not directly cause disease. Moreover, the cutoff of at least 1% prevalence for a variation to be classified as a polymorphism is somewhat arbitrary; if the frequency is lower than this, the allele is typically regarded as a mutation.

SNPs are important as markers, or signposts, for scientists to use when they look at populations of organisms in an attempt to find genetic changes that predispose individuals to certain traits, including disease. On average, SNPs are found every 1,000--2,000 nucleotides in the human genome, and scientists participating in the International HapMap Consortium have mapped millions of these alterations.

The DNA in any cell can be altered through environmental exposure to certain chemicals, ultraviolet radiation, other genetic insults, or even errors that occur during the process of replication. Sickle-cell anemia is a disease caused by a change in a single nucleotide, and it represents just one class of mutations called point mutations. The alteration of a single nucleotide in the gene for the beta chain of the hemoglobin protein, the oxygen-carrying protein that makes blood red, is all it takes to turn a normal hemoglobin gene into a sickle-cell hemoglobin gene. This single nucleotide change alters only one amino acid in the protein chain, but the results are devastating. Molecules of sickle-cell hemoglobin stick to one another, forming rigid rods. These rods cause a person's red blood cells to take on a deformed, sickle-like shape, thus giving the disease its name. The rigid, misshapen blood cells do not carry oxygen well, and they also tend to clog capillaries, causing an affected person's blood supply to be cut off to various tissues, including the brain and the heart. Therefore, when an afflicted individual exerts himself or herself even slightly, he or she often experiences terrible pain, and he or she might even undergo heart attack or stroke - all because of a single nucleotide mutation. 

Mutations can also alter the way a gene is read through either the insertion or the deletion of a single base. In these so-called frameshift mutations, entire proteins are altered as a result of the deletion or insertion. This occurs because nucleotides are read by ribosomes in groups of three, called codons. Thus, if the number of bases removed or inserted from a gene is not a multiple of three, the reading frame for the rest of the protein is thrown off. 

Changes in the DNA sequence can also occur at the level of the chromosome, in which large segments of  chromosomes are altered. In this case, fragments of chromosomes can be deleted, duplicated, inverted, translocated to different chromosomes, or otherwise rearranged, resulting in changes such as modification of gene dosage, the complete absence of genes, or the alteration of gene sequence. The type of variation that occurs when entire areas of chromosomes are duplicated or lost, called copy number variation (CNV), has especially important implications for human disease and evolution.
