---
title: "Chapter 10.1: A Career in Psychiatric Genetics (Video Transcript)"
---

**Title**: How does Genetics Affect our Mental Health?

**Presenter(s)**: Cathryn Lewis, Alex Curmi

*You have found the "Thinking Mind" podcast \[Music\].*

**Alex**: Professor Catherine Lewis, thank you for coming on the show.

**Cathryn**: Pleasure, Alex. Thank you for the invitation.

**Alex**: I'm sure there's a lot that we're going to get to talk about in terms of genetics, psychiatry, psychiatric conditions, psychology, and how we can, using the art of maths and statistics, come to unravel some of these mysteries. But one of the great things about talking to interesting guests such as yourself is the ability to learn about Career Development and career paths, and to learn that career paths aren't always linear. And maybe you could tell us a bit about how, how do you become a professor of genetics, statistics, epidemiology,

**Cathryn**: yeah, yeah, So my background is, it's not in Psychiatry or psychology, but in maths. I did a first degree in very pure maths, um, and because I was passionate about maths when I was at school and really enjoyed it. But as the studies went on, I realized that that sort of esoteric theoretical side of Academia was not really what I was interested in. I wanted things that were much more practical, that were much more aligned with solving problems in everyday life. And so I moved on to do a master's degree in statistics and did a lot of data analysis. Statistics is a fabulous area to study because it gives you access not just to the math side, but so many different areas that people use statistics in. And I was lucky enough during my PhD to start analyzing genetic data and realized that I'm was really interested in it and also that it was a blossoming, developing area of medical research. And so that launched me in my research career.

Um, I should say that I've worked across different medical areas during my career. I started working in cancer, looking for genes for breast cancer, and I'm a very, very minor author in the paper that found the *BRCA1* gene with high-risk variants for breast cancer, for example, and I've worked in autoimmune disorders, and really applying my statistical techniques where they can be useful. But what I've focused on in the last 15 years is working in the genetics of mental health disorders and of Psychiatry. And like many things, this was a very serendipitous chance. I remember presenting a poster at a conference on autoimmune disorders, and a psychiatrist came up to me and said we could do this in schizophrenia, and I started working with him in schizophrenia. And then Peter McGuffin, who was head of the social genetic and developmental Psychiatry Center where I am now am, saw the potential to bring my skills into mental health genetics and approached me, and 15 years later, I'm, um, you know, fully embedded in the genetics of Psychiatry.

**Alex**: Have you found that serendipity is an important part of forging a career path?

**Cathryn**: Um, for me, it certainly has been. I know people have different approaches to planning their career; mine has always been quite short-termist. I've always, you know, I've always really enjoyed what I've done, and I've taken decisions based on, "Oh, that sounds like a really good project to be involved in," "Oh, I'd really like to work with them." So, I've never had a, you know, a long-term goal of what I would achieve, and I know that's not the sort of advice that,

**Alex**: it's not the standard, right?

**Cathryn**: It's not\... it's worked very well for me, and I've really enjoyed the flexibility of academic careers to hop around and to build up experience and to learn, you know, from different projects and different people - things that really produce a richness to the next, uh, the next thing that you do. And I should also say, perhaps, that I worked, I worked part-time for 10 years, years while my children were young, and again, really enjoyed that flexibility to continue with the bits of the role that were important to me.

**Alex**: So you had the kind of experimental attitude towards your career, trying different things, and you were guided by your sense of fascination, which is actually career advice I give to people all the time because I think we're conditioned by our educational system really to meet goals that are set by other people. And I also think that fascination is a kind of sense you can develop. The more you're led by it, the more you can actually sense how actually interested or engaged am I in this particular thing. But so many people do things that they're not engaged with for their whole lives, so it's nice to hear that you've been able to escape that particular trap,

**Cathryn**: yeah, yeah, now that's really good to hear that perspective on it and I agree with that kind of fascination, and of course, that's what scientific research and exploration are all about. But maybe I can put in a plea, you know, I come from a maths background, and a lot of science now is about large numbers, it's about AI, it's having the skills to not only do molecular work (you know, in the lab or working with people) but to be able to analyze that data and put things together. And I would recommend anyone that gets the chance to develop their skills further in maths or statistics, that really does open doors to the breadth of different things that you can get involved in. And you know, particularly, young people, if they get the chance to study maths, you know, at a level beyond the age of 16 where it's compulsory in the UK, you know, even downstairs dream that really opens doors having those skills and that showing your ability to be able to think analytically. And as a mathematician, of course, I'm biased, I do think mathematical skills open doors in many fields.

**Alex**: Absolutely. So maybe you could tell us a bit about statistics. How does statistics help us to unravel some of the mysteries, particularly in Psychiatry, that we're trying to figure out?

**Cathryn**: So one of the things that statistics enables you to get a handle on, is the risk of something happening, and that's what we're very interested in as individuals. You know, starting something very basic that we think about a lot is family history of psychiatric disorders. So we know, you know, we know from scientific studies, from our personal experience, that mental health disorders tend to run in families. We very often see that someone who's diagnosed with depression, one of their parents or a more distant relative also has depression. And looking at families, we've been able to get risks of people developing a disorder themselves given their family history.

But I think people are not always very good at interpreting risks appropriately, and we see this very much so in newspapers, for example. We see that something is told that it increases our risk of something really bad happening by five times, and that's quite scary to see, to know that, "Oh, I've drunk too much coffee, I might be at five times the risk of something else happening." But that five times is a relative risk, that's compared to it not happening. The other piece of information that we are not good at looking at is the absolute risk. So if the chance of something happening is very rare, say happening one in ten thousand times, then of five times, it's still very unusual that it happens. And I think we're very bad at interpreting risks because we need to put together that relative risk, which is often quite scary, with the absolute risk, which can bring that back to being quite reassuring.

**Alex**: yes, so, so relative risk is like how, how much more likely are you to develop a condition given a particular state of affairs? That's relative risk...

**Cathryn**: Exactly.

**Alex**: Risk is just in the population, who's going to develop this? How likely is it to develop a condition,

**Cathryn**: yeah, exactly. And so, to bring that back to mental health, so in schizophrenia, for example, we know that someone who has a parent who's been diagnosed with schizophrenia is, you know, maybe eight or ten times more likely to develop schizophrenia themselves, and that's a really scary number, and I know there's a lot of concern, quite justifiably about that, but to put that in context, if the population risk of schizophrenia is about one percent, then being at an eight-fold increased risk of developing schizophrenia is a risk of eight percent. So yes, that eight percent is higher than the population risk, but that still means that there's a 92 percent chance that that doesn't happen, so it's actually doesn't develop schizophrenia.

**Alex**: so really, we don't... when we see genetic data, particularly I find an issue is when scientific data is filtered through the media because the media obviously are incentivized to produce something eye-catching or sensational. But leaving that aside, we don't have good intuitions about how to evaluate risk as we see it as reported by scientific data, it sounds like.

**Cathryn**: Yes I completly agree with you, and there is, you know, as you say, the newspapers, journalists have to, you know, sell their news, and so they tend to report the things that are most likely to be eye-catching, you know, more sort of clickbait. And so they tend to report the relative risk rather than the more reassuring absolute risk.

**Alex**: The other thing, I guess, the very traditional view of genetics is that our DNA is quite has a very high determination on what happens. You know, if you're, if you have the particular genes for condition, you're gonna get that condition. That's how we tend to think of it classically. But we know more and more that there are some conditions which have a huge amount, a huge variety, of genetic influence, so much more than one gene. Say if you have a condition like Huntington's disorder, that's one gene, and if you have the gene, you're going to develop that condition. But most things, is it fair to say that most things aren't like Huntington's?

**Cathryn**: It's very fair to say so. So some traits are exactly like Huntington's, like cystic fibrosis or variants in the BRCA1 gene for breast cancer, where those genetic changes on their own put someone at a very high risk of developing a genetic disorder, and that's the sort of genetics that we're taught in school, and it leads us to think about genetics as a black and white, yes, no, you know, we're at risk or we're not at risk.

**Alex**: You have the fat gene, exactly, exactly.

**Cathryn**: Well, and can I say we all have the fat gene, we all carry that gene, but what differs between us is the changes in that gene, so specific changes at the level of the DNA variants that we carry, and that's what makes a difference between us.

**Alex**: Tell me more about that.

**Cathryn**: So, our genes are made up of a long string of DNA variants, so the base pairs A, C, G, and T, and about 99% of our genome is exactly the same. You know, you, me, and everyone listening to this podcast will have exactly the same base pair at exactly the same place in our DNA. But one percent of our genome may differ between us, and our genome is over three billion base pairs long, so one percent still gives us quite a lot of opportunities to differ, and some of those changes have a very big impact on our risk of different diseases, different conditions. But most of those changes that we see in our DNA have a very modest effect on disease risk, and much of my research is in the genetics of depression, and for the last 10 years, we've been carrying out studies to identify the genetic attributions to depression. And we do this in a classic epidemiological design, that's a case-control study. We collect, we perform recent studies with groups of people who've been diagnosed with depression, and we compare their DNA to people either from the general population or people that we know have not been diagnosed with depression to date. And we step along the genome looking at multiple different places on the genome, and we look at the frequency of that change, and we say, okay, this site in the genome, people either have a C allele or an A allele, there. What's the frequency of that A allele in people with depression, and with people without depression? And then we do a very simple statistical test and say, does that differ? And we do that at several million places through the genome, and by carrying out really careful statistical tests, we can identify specific changes that seem to increase people's risk of developing depression,

**Alex**: so specific, very specific genetic differences that are more correlated with someone having depression.

**Cathryn**: Exactly, but the actual risk conferred by each of those individual changes is very, very low. We're not in the single gene Mendelian disorder territory that we've been with Huntington's disease. We're now in a polygenic genetic model, which is what seems to be underpinning depression, schizophrenia, bipolar, or all and also most physical disorders that really have an impact on people's lives. We're not looking for single genetic changes; we're looking for genetic changes spread across the genome, each of which have a very modest effect on people's risk of developing a disorder. But when we put them together across the genome, that gives us much more information on risks.

**Alex**: So really, the role of statistics in all this is to churn through huge amounts of data and figure out what are the patterns, what are the meaningful patterns that we can extract from this data?

**Cathryn**: Exactly, and this really is big data analysis. And it's big data in two ways. Our genome is very big, and we need to look, you know, across the whole of that genome. And also, because the risks conferred by each change are very modest, we need really large studies here to be able to identify those changes. So in depression genetics, 10 years ago, we carried out a very large international study through the Psychiatric Genomics Consortium that pulled together internationally 10,000 people with depression and 10,000 people without depression. And we were really excited by this. It was the largest study that had ever been performed in depression genetics. And we found absolutely nothing.

**Alex**: Wow.

**Cathryn**: And this was a massive study; there were millions of research funding that had gone into this. And of course, it was, you know, 10,000 people, you know, their time and their energy, their participation in the study, and that was hugely disappointing at the time. And we stepped back and we thought about this and we looked at what had happened in other studies like in schizophrenia and bipolar and in studies in heart disease and rheumatoid arthritis that have been more successful. And we started to think, well, what is it that's different about depression? And we realized a couple of things. That first of all, you know, depression is much more difficult to diagnose and other many of those other disorders where genetic studies were being successful 10 years ago. And so there was probably a lot of heterogeneity in those studies that we weren't taking account for. And also, the genetics of depression... genetics is a much more modest contribution to risk in depression than it does in schizophrenia. So that when we look at twin studies, the heritability of depression is less than 40 percent compared to up to 80 in schizophrenia. So that means that in addition to genetics contributing, there's much more scope for other risk factors to contribute. And we think of this, I think of this in the context of the biopsychosocial model. So we can investigate the bio part, but we need to acknowledge, particularly in depression, that there's much, much more going on from the psychosocial part of this.

**Alex**: This is such an interesting conversation because obviously you're coming from the big data side of things, and I'm a clinician. And it's so interesting because from what you're telling me, it makes sense in light of my clinical experience. That, from my anecdotal clinical experience, it makes sense to me when you're telling me that there's a huge or a bigger psychosocial influence in depression with schizophrenia because with depression, for example, you can see very straightforwardly and intuitively how lifestyle factors, whether someone has a job, whether they have a good relationship, whether they have friends, whether they have whether they have meaningful work can influence whether or not they become depressed. And one so, let's, let's continue on the polygenic front. So, are we close to figuring out, for example, how many genetic changes might be involved in a condition like schizophrenia, or is that still mysterious, the total number of genetic changes involved?

**Cathryn**: We are making substantial progress. So, I talked about the depression study where we'd found absolutely nothing.

**Alex**: You know, why did you guys find nothing, do you think?

**Cathryn**: Because um, because um, statistically, studies are always a mix of signal and noise, and you need to get enough signal to stand out against the noise. And that study, even though it had 9,000 people who generously contributed to our research, it just wasn't enough. And so, having stepped back and thought about this, it had... we had the confidence to say we just need to continue, this is about sample size and uh, and so we went out, we increased the sample size substantially, we collaborated with a lot more people, and our latest genetic study, which is still unpublished, we've been talking about it in conferences, we now have identified 500 genetic variants across the genome which we believe play a role in depression.

**Alex**: How many people did it take?

**Cathryn**: That's a really good question. It's taken half a million people with depression to find that. And some people, thinking of this in the biopsychosocial model, some people say, "Well, why do you bother? If you really need that many people to find these very modest genetic changes, you know, well, shouldn't we be focusing our time and our energy and our money on doing different things to solve depression?" And I think my pushback on that is that we need to be doing everything that we can in our depression and all mental health disorders. You know, it's a major problem for society, for those people who've been diagnosed, and the families that care for them. And we need to be doing everything we can, taking every angle that might help us diagnose, treat, maybe even prevent these disorders. And genetics allows us access to that underlying biology, and that's really difficult to get a handle on in mental health disorders. Exactly, and we have no biomarkers; you know, we can't do a blood test and identify people who are at high risk or use that for a diagnosis. And so, genetics, I'm hoping, will give us a handle on that underlying biology. It'll tell us more about why people get depressed, what the pathways are for that, what are the changes in the brain, in the body, that can lead towards depression. And then, of course, that gives us perspectives on how we could help prevent that. You know, does it give us new new drug targets that we might be able to develop

**Alex**: or other interventions like brain stimulation is becoming more involved?

**Cathryn**: Yeah, exactly, yeah.

**Alex**: It's really interesting. So, I talked to this week, I talked to Nolan Williams, who is a psychiatrist at Stanford, and he is an expert in brain stimulation. And he actually said from his work, which is doing very intense brain stimulation treatments, magnetic stimulation, he's found out, by doing that and studying people in MRI scans, that there's a subset of people with depression where the depression seems to be correlated with, if not caused by, one area of the brain activating before another area of the brain - the anterior cingulate cortex activating before the dorsolateral prefrontal cortex (I know that's a mouthful, I'm sorry). And through stimulation, you can reverse that temporality, where one area gets activated before the other and regulates it, and that seems to have this amazing effect on people's clinical presentation; they get a lot less depressed.

So absolutely, the biology is foundational. Do we know, do we have a sense of how many, or how many changes have we found genetic variances with conditions like schizophrenia, bipolar, and is there an overlap between those two?

**Cathryn**: For schizophrenia and bipolar disorder, we've found over 200 variants for each of those. But for all of these, we know that that's the tip of the iceberg. You know, there is a lot more to find. There is overlap between them, there's overlap between all psychiatric disorders, and the model, the way that we think about this currently is that there are probably some genetic changes, some genes that are involved that are relevant to the brain in general and across all different diagnoses. And then there are likely to be other variants that are unique to maybe subgroups of disorders or single disorders and conditions themselves. And so, but working across diagnoses and working transdiagnostically as well, genetics again should help us to do that and show where the similarities and where the differences lie.

**Alex**: Because really, what this genetic picture (I'm not sure if you're aware of this) is very challenging to our diagnostic framework as clinicians because we put diagnoses in categories or buckets. We say, this person has a psychotic condition such as schizophrenia, or this one has a mood disorder such as bipolar when it seems to be somewhere in between those two, we call it schizoaffective disorder or depression, or what have you. And this picture where it's very continuous, where it's loads of different genes and somewhere can be at any point on a spectrum, and then those genes, which I'd like to talk to you about later, have to interact with environmental stimuli. That paints a picture where people really aren't in one category or another, but everything is kind of a spectrum. Would you agree with that notion?

**Cathryn**: Yes, and probably a multi-dimensional spectrum, and none of this is to be easy, and how might genetics help with that? Well, I mean, you've talked about people not fitting in with a particular diagnostic group, and I know people's diagnoses change across life, and their symptoms change. And I would hope that genetics might be able to give us a perspective on that because our genetics stay constant all through life. And that's one of the real values of genetic tests, is that the variants that we're talking about, we inherit those from our parents, and they remain stable all through life. And so if we could get some information on how genetics might help predict prognosis, how might people's mental health play out across their lifetime, what does their genetics indicate they might be at highest risk of developing, I would hope that that sort of information might become useful diagnostically. It's never going to be the whole answer; nothing is going to be the whole answer in psychiatry; it's all too complex. But we need to be taking, we need to be working together. I, as a geneticist, need to be working with you as a psychiatrist. We need to be working with people who do brain stimulation and do neuroimaging and working with psychologists and sociologists and looking at this in its entirety to see how we can make progress.

**Alex**: I mean, as a clinician, I think having more genetic information about a given patient would be incredibly helpful. So if, because we get wrapped up in diagnostic mysteries all the time, and it can be very puzzling, and of course, people change subtly from day to day if they've had enough sleep, what medication they're on, but if we can get some hard data, for example, tests which are sophisticated enough to say, "This person has 150 of the 200 changes that are associated with bipolar affective disorder, and they have 50 of the ones associated with schizophrenia," for example, I can really see that that would provide a huge value to clinicians and to patients themselves. Because a lot of the trouble of being unwell is the huge amount of the mental suffering of being unwell is the mystery. And obviously, like you're saying, we don't want to take a too hard line approach where genetics is everything, but anything that can help us shine the light on these complexities can be very therapeutic I think.

**Cathryn**: That's a really good point, and we're starting to do that through polygenic scores. Now, these individual variants that we have, the 500 variants for depression, over 200 for schizophrenia and bipolar, individually, they give us tiny amounts of information. We can't use them on their own. But when we put them together across the genome, we can construct polygenic scores, which does exactly what you've just said. It looks at how many of those risk variants does someone carry. Now, you know, we all carry some of those risk variants, and most people will carry an average number, so their genetics of depression won't tell them very much; they'll have an average loading for depression. But some people might carry high polygenic scores for depression because, by chance, they've inherited more of those risk variants from their parents than other people. And so that's something that we're starting to look at: how these scores allow us to look at the spread of risk in the population. So, so far, the amount of risk that they explain is quite low. For example, in schizophrenia, where perhaps we have the strongest genetic profiles to date, if you look at the people who have the highest polygenic scores, so the 10% of the population who are at the highest risk and the 10% who are at the lowest risk, the difference in their risk of schizophrenia is about 16-fold, to use a relative risk.

**Alex**: So the 16 times more likely.

**Cathryn**: yes, exactly. So the 10% of people with the highest risk are 16 times more likely to develop schizophrenia than the 10% with the lowest

**Alex**: which is fairly substantial because the risk of schizophrenia is about one percent at baseline, so that has a 16 percent,

**Cathryn**: but that does leave out the middle 80 percent of that distribution and another way of looking at that is to say, well, what might we want to do about this? Another perspective on this is to say, well, if we could identify people who were at the highest one percent of risk, so those one in a hundred people who have got the very highest genetic loading for schizophrenia, and we compared their risk to everyone else, what would that be? How big would that be? Is it really worth knowing, identifying that the very, very highest? And there, there's a six-fold increase in risk, so that's much more modest. It's really saying that even though we know quite a lot about the genetics of schizophrenia, it's not in itself giving us enough signal yet that it would be useful.

**Alex**: But did you say, so the one percent, the top one percent, have a six-fold increase compared to everyone else? Which proportion had the 16-fold?

**Cathryn**: Uh, so the 16-fold risk was looking at the top and bottom ten percent. Okay, okay. So they're looking at the real extremes, and this is, you know, it's statistically valid, but it's a statistic that says, "Right, if we look at the real extremes, what does that tell us?" And that's really useful information for research studies, we might use that a lot to say to compare, you know, people who've enrolled in research studies who have the highest and lowest risk. But that's not so useful for you as a clinician. And as a clinician, I think, you know, focusing on the people at the very highest risk and saying, "Does this tell me very much?" and at a population level, I think it doesn't. But where it might be useful is, you know, where someone's showing symptoms. So maybe someone's had their first episode of psychosis or in an ultra-high-risk group, you know, including genetics together with all the other information you have on your patients, that I think where it might be useful.

**Alex**: And it could help to advise individuals or their doctors on what lifestyle factors to encourage or avoid. So something we talk about a lot on this podcast is the association between cannabis and psychosis, which is a bit of a tricky one to explain in that the majority of people who use cannabis won't encounter any issues, which is important when you're thinking about legal policy and things like that. But a substantial minority or a significant minority can develop a psychotic illness, and this has been studied epidemiologically by Marta de Forte in a huge multi-centered trial where there's a clear correlation between cannabis use and development of psychotic symptoms. And I think even anecdotally, many, many people know that one person when they were growing up who smoked a lot of cannabis and ended up developing a mental health condition of some kind. So do you think these polygenic risk scores, particularly when they're more sophisticated, when we know more of the genetic variants, we'll be able to tell us, "You need to stay away from this, that, or the other?"

**Cathryn**: I think that would be really useful, and we're certainly heading in that direction. Um, and I have the pleasure of working with Marta de Forte and hearing about her wonderful research. And I think that's really useful or potentially useful in a public health message. Um, but the reason that it's useful there is because we have the genetic signal and we have an intervention. You know, we know that, well, with a really high genetic loading, maybe you really shouldn't smoke cannabis. So knowing the genetics is not enough; we need to know what we do about that, and I think the genetics of schizophrenia and cannabis is the perfect example of that.

**Alex**: Or someone at high risk of depression, say as a teenager, you could teach them certain skills, cognitive-behavioral skills around mental flexibility, because mental flexibility is really important for treating and preventing depression, for instance.

**Cathryn**: Yeah, so exactly. And also maybe the potential of exercise, which many people would say has a role in both preventing and hastening recovery from depression. Um, and it's very easy for us sitting here to come up with these potential examples of where it might, where genetics might be useful. But, you know, we're not, we're not very good at assessing risks; we're not very good at dealing with genetic information because as a society, we've never really had to do that before.

**Alex**: It's counterintuitive.

**Cathryn**: It is. And I think I worry slightly about if we're going to start telling teenagers, "Well, you shouldn't smoke cannabis because you have a high genetic risk of developing schizophrenia or psychosis." That's a really difficult message to give a teenager, and I think...

**Alex**: it's not easy marketing.

**Cathryn**: We've got a huge way to go to make sure that our communications of genetics are done in a way that's helpful to people, that is not scary, that's going to be advantageous, that's not going to increase stigma, but it's going to be helpful to everyone involved.

**Alex**: And I suppose in a way that's accurate because, you know, we're having a whole long phone conversation, just to unpick the different pieces of this, and we have historical examples, obviously, of genetics and a genetic argument being misrepresented in order to justify an ideological goal or a political goal, things along those lines. So, there's one issue with our species, I think, is we develop technology a lot faster than we develop an ability to understand it ethically. If we develop atomic weapons and then we have to figure out how we're going to think about this in an ethical framework, and I think the same could be said with genetics because maybe I could ask you, do you think there's a potential dark side to genetics and improving our genetic understanding, that it could be used for harmful means in the future?

**Cathryn**: I think the potential is certainly there, and we need to be really careful about how we talk about genetics and increasing people's genetic literacy, so that they understand that genetics is not just a yes-no, that people are at high risk of a disorder or not, but it is a continuous measure. Measuring someone's genetic liability to depression, to schizophrenia, you know, it's like measuring someone's height; it's not a yes-no, it's a, you know, people are most people are average risk, some are at high risk, and some are at low risk. But we've also seen, I think, areas where genetics can be misused. So, we've seen the genetics between different population groups around the world being used as a justification for discrimination, being jumped on by the far right to justify their perspectives. Another area that we're seeing that worries many of us in genetic research is these polygenic risks for disorder being used in places that are not appropriate. And we see, we've talked about the schizophrenia risk being useful, but not on its own; it needs to be in context with everything else. But there are some companies that are offering genetic risks as part of embryo screening in *in-vitro* fertilization, and they do that because we have the technology, and they're applying that. But I think we have to be really careful in those cases that what we're that what, the way that we're applying our genetic information is really underpinned by sound ethical and statistical concerns.

**Alex**: Do you think, in the case of those companies, is the issue that they're falsely representing how useful the technology is, how accurate it is, or is it just that it is actually has proven utility in screening for certain conditions, but they're just kind of marching ahead without any kind of thought as to the ethics?

**Cathryn**: I wouldn't accuse any of those companies of marching ahead without considering the ethics; that would be unethical of me. But from what I have read about the science and the risks conferred, it is very difficult for me to see that making a decision about which embryos to implant, on the basis of, for example, a polygenic score for schizophrenia, is justifiable. And of course, the concerns downstream are, you know, the impact on stigma, the impact on this idea that we could remove mental disorders by a simple genetic test. It's really worrying, it's completely inappropriate, and I think we need much broader societal discussions.

**Alex**: And it sounds like there's still too much mystery in this whole process to make those claims and to market these things as sort of... I can easily fantasize about how the marketing has a higher degree of certainty.

**Cathryn**: Exactly, and I think that there is so much noise. I mean, to put this in context, the risks that we have for schizophrenia account for about seven percent of overall understanding of risks of schizophrenia. So we can estimate what's going on in that seven percent, that leaves 93 percent that we're not including in that calculation, in that assessment.

**Alex**: Um, how does the environment interact with our genetics to influence a particular presentation?

**Cathryn**: That's a really good question, and we've this concept of gene-environment interaction has has been a part of research studies in for decades now, and our understanding is that for most examples, that it's not an interaction but it is an additive, a combined effect and so what I mean there is that the genetics and the environment combine together to cumulatively give a risk of disorder, but they don't interact on a statistical level. Yes, so what I mean by interacting here is that, well, let's look at this the other way around, that genes and environment seem to contribute independently, so someone's genetic risk to a disorder will give them a certain amount of risk, their environmental component will give you another risk, and we can just add those together. If there's an interaction, that's saying that the environment, the way that the environment contributes depends on the genetics, and that's not what we're seeing in most cases. So, you know, our intuitive understanding, I think, or a useful thought was, well, if people have really high genetic risk and a poor environment, maybe that will make their risks soar, you know, maybe the combination of two bad things will really lead to a much, much higher risk.

**Alex**: You think of a compound,

**Cathryn**: yeah, but that's not what we're seeing, we're seeing that there's an additive effect, and the evidence for that is still quite modest in mental health disorders, but that's what we're seeing in heart disease, say, where we've got in a much better handle on traditional risk effects, you know, from obesity, from cholesterol, and we combine that with the genetics, and they do seem to be additive. So, I always, as a statistician, push back when people talk about interactions because what we seem to be seeing is more of an additive joint effect.

**Alex**: that maybe doesn't fit, maybe there's a that doesn't fit with the what we understand about some of the biology because my understanding is that certain genes can be switched on or off depending on environmental triggers, but that concept, the idea that genes can be switched on or off, does that fit with your statistical understanding?

**Cathryn**: I think it does just because these models, you know, are complex, and I don't think that that model as you've described it would conflict with an additive effect. But we have a long way to go, I mean, you know, we've talked about the rapid progress we've made in genetic studies over the last 10 years, and as our understanding improves, as we know more about the genetics and the biology, we may, you know, we may well find interactive effects, but what I think we can say is that they're not, you know, they're not the overwhelming signal we're finding.

**Alex**: because I think maybe the way I was using interaction was different from the way you I think you meant interacting mathematically and I meant interacting as in the environment, the environmental stimuli switching on a gene or off.

**Cathryn**: Yes, you're right, yes, the statistical and this biological terms are slightly different and emphasize that fact we need to work together, we need to combine all these different perspectives.

**Alex**: So we've talked a lot about psychiatric conditions, you know pathological states, but let's talk about a non-pathological but still psychological state like personality. Do does genetics have an influence on our personality?

**Cathryn**: Genetics does have an influence on our personality, and what a question that we should really be asking is how big is the genetic influence? Um, and the influence on personality is fairly high, and of course, that has an impact for mental health as well. So neuroticism as a personality trait is highly correlated with depression.

**Alex**: And what is neuroticism? I should point out to our listeners. Okay, there's two things I want to point out. First thing is, there's the way personality is used technically. I mean, that's the way we use personality colloquially, and we run into this when we, for example, talk about this or personality disorders. When we're talking about personality technically, we mean a set of traits that are stable across the lifetime that influence someone's interaction with themselves, the world, and other people. That's my elevator pitch definition of personality. Um, I think that's really important to keep in mind. That was the second thing I was going to point out, which I can't remember now. Um, neuroticism is used in many different contexts in Psychology and psychoanalytic literature. What do we mean when we talk about neuroticism in this context?

**Cathryn**: So in this context, neuroticism through a series of questions that, um,

**Alex**: so I think of it as a sensitivity to stress. So how much emotional dysregulation do you experience per unit stress? Like you take person A and person B, they both lose their jobs, person A will have a particular emotional response and person B will have a particular emotional response, and it's quite likely they'll be different. People are different, they respond emotionally differently to roughly equal units of stress. But neuroticism doesn't have a great name for PR, so that's a problem that's happened, but, um, yeah, how, so how, on average, what kind of influence is genetics having on our personality?

**Cathryn**: So genetics does have an influence on personality, and we see that from studies all around the world, from twin studies and genetic studies. You know, we know there's a big contribution, um, in exactly the same way as there's a contribution towards mental health disorders, and it's exactly the same sort of model that it is polygenic. You know, that we're starting to identify individual variants that contribute to personality traits, to well-being, to whatever way we want to measure someone's personality. But again, each of those individual variants has a very small effect, um, and we're again starting to identify those polygenic profiles that that contribute to someone's personality.

**Alex**: I think people will have an inherent resistance to the idea that there is some genetic influence on personality because it has that flavor of biological determination, and personality is really important. So if you take a trait by conscientiousness, that's people conscientiousness is highly correlated with life success, and that subdivides into industriousness and ordinariness. So industriousness is literally how hard you work. So obviously, you could see how that would have a correlation with success. If people were to find out that whether genetically or otherwise they have a particular, because you can do a test and find out what your personality is or what traits you're high in or low in, is that is that a, is that a prison sentence? Are you bound by that? Or are there things that you can do to change your personality traits?

**Cathryn**: I want to push back on that phrase prison sentence, absolutely not. None of the genetics that we're talking about in this context, these polygenic models, none of them are deterministic. You know, they are probabilistic, and they combine with the environment, with your family, you know, with society that you're in. They can give you a certain inherited predisposition that might push you down a certain road to start with, but that genetics is always going to be mixed with everything else that you're exposed to.

**Alex**: What are some tips or maybe principles you've discovered for building a successful career in science? Which is a very difficult thing to achieve. What are some things you've learned along that along that road?

**Cathryn**: So building a successful career, so many different things. I think flexibility and resilience is one of it. Science itself is serendipitous, you know what, whether the studies you're involved in, you know, get funding, have a successful result, are fashionable, and are popular in the scientific environment, all of those depend quite a lot on luck. It depends a lot on who we work with, you know, having supportive mentors and supervisors who can assess your strengths and see, you know, how you can develop best and what direction you could perhaps be moving in that would help you thrive. Um, it is really important. But also that ability to bounce back, you know, to be working in that personal environment, that professional environment where when your paper is rejected by a journal for the third time or your grant application doesn't get funded again, you know, that being able to think "right, what's Plan B here? where do I go next? and how can people help me achieve what I want to achieve?"

**Alex**: So your attitude towards failure is very important.

**Cathryn**: Yes, I mean, you know, I sit here as an academic, as a professor, but working in a university is only one of the places where excellent science takes place. A lot of my PhD students and a lot of my postdocs, you know, don't stay in academia but move into industry, into the pharmaceutical industry, into biotech, into policy work, into government and third sector organizations. There are so many different fascinating careers from a scientific basis where our trainees can thrive, and I encourage that breadth of discovery across all the options available.

**Alex**: And the other thing I've observed about science from the outside, I've never done research myself. Is that it requires this very delicate balance of curiosity and open-mindedness on the one hand, and then being skeptical and detail-oriented on the other hand. And those two things don't often go together, but from what I've observed, the very best scientists seem to be able to merge both, or at least the teams and labs. The best teams and labs have people who are good at both. Has that been your experience, or has it been something different?

**Cathryn**: I like that perspective of looking on science. Um, and you've talked about one person having both of those. For me, much of this has been about teamwork, you know. So you get a wonderful discovery, you know, you press the button on the computer and you get your highly significant p-value, and you jump up and down an enthusiasm with this in the team meeting. And then, you know, the good scientists that work with you will be saying, well, what about this, and did you account for this, and have you controlled for this? And it will be that balance of that excitement, that moderation, that checking, that doing the sensitivity analyses.

**Alex**: Where do you see yourself? Are you the enthusiast or are you the moderating influence or are you both?

**Cathryn**: I'm a statistician. I am a skeptic, and I'm a skeptic about every single number that people present to me, and they have to justify me that and show me that, you know, whatever they do to their data, whatever perspective they have on that study, that effect does not disappear, then I will believe it.

**Alex**: Okay, we should work together then because I'm definitely an enthusiast.

**Cathryn**: It would be a great partnership.

**Alex**: Um, you were a listener of this podcast, and I am constantly trying to make it better, and I'm constantly asking, you know, what is it that you get from listening to it and how could it be better?

**Cathryn**: Um, I'm a huge fan of the podcast. I've learned so much, um, both within my field and well outside my field that has really helped me, you know, develop as a scientist and working in mental health, and really getting an appreciation. Um, I mean, as we've talked about, I'm a statistician. I often come at things from a numeric perspective rather than a people perspective, and listening to podcasts like this has really made me appreciate the real diversity of work that goes on and the value of people with lived experience, and how, you know, getting people involved in research, whatever their experience is, is essential for people like me to do good research. So, I would say just carry on that diversity.

**Alex**: I need your moderating more \[laughter\]

**Cathryn**: More genetics, more biology, but it's that diversity that, for me, it's the real power of your work,

**Alex**: Professor Lewis. Thank you so much.

**Cathryn**: My pleasure. Thank you for having me, Alex.
