---
title: "Chapter 9.2: Mendelian Randomization (Video Transcript)"
---

**Title**: A two minute primer on Mendelian Randomization

**Presenter(s)**: George Davey Smith, TARG Bristol

Epidemiologists are interested in understanding factors related to health and disease. The smokers tend to die younger than non-smokers; it certainly looks that way, but disentangling cause-and-effect can be difficult. Smokers are different on average from non-smokers; they're more likely to drink heavily and have less healthy diets. But even if we measure these confounding factors, we may not measure them perfectly, or there may be others we haven't measured. Also, as people become ill, they may cut down or give up smoking, which could wrongly suggest that reduced smoking leads to worse health.

We could randomly assign 50,000 people to smoke and 50,000 people to not smoke, and follow them up to monitor their health. This removes the possibility that any other factor could be responsible for any differences we see in their long-term health, but this is neither ethical nor practical.

Fortunately, we've all been recruited into an experiment without knowing it at the point at which we were conceived. Our genes, which have passed on randomly from generation to generation, influence how much we eat, drink, smoke, and more. These genetic influences are not affected by anything else you may or may not choose to do in your life; they're not related to confounding factors.

We can use this knowledge to learn about cause and effect, grouping people according to their genetic code. This method is called Mendelian Randomization. For example, smokers carrying one version of a gene called CHRNA5 tend to smoke less heavily than those who carry a different version. When we group people according to which version of this gene they have, we find that the people with the version of the gene associated with heavier smoking do indeed die younger. But is the gene influencing how long we live in some other way? We don't think so. When we look at the same gene in non-smokers, there's no effect on life expectancy. So, that must be driven by smoking.

Using this method, you can show that smoking causes lung cancer, heart and respiratory disease, and many other diseases, but it has not seemed to influence depression or anxiety. Mendelian randomization has already begun to tell us about factors that influence our risk of disease. Now, we're using the same approach in other ways to look at several risk factors together and to look at what influences disease progression, which may help us develop new treatments.
