---
title: "Chapter 2.1 Organization of the genome (Video Transcript)"
---

**Title**: An Introduction to the Human Genome

**Presenter(s)**: HMX Genetics, Harvard University

Humans around the world have much in common, but also enormous diversity. Some of the differences between each of us come from our environment and life experiences, but our DNA plays an important role in determining our appearance, our traits, and our health. There are thousands of genes in the human genome sequence. Changes in individual genes can determine if we have freckles, can digest lactose, have wet or dry earwax, are red-green color blind, or are likely to have blue eyes or think broccoli tastes better. Individual genes can also determine if we will develop sickle cell anemia, cystic fibrosis, or Huntington's disease. Multiple genes act together with our environment to determine our hair and skin color, our height, our weight, our blood pressure, and our risk of developing type 2 diabetes, depression, cancer, some autoimmune disorders, and many other conditions.

In spite of all these potential differences humans are 99.9% genetically identical. How is it possible that we are all so similar and yet so different? Let's zoom into the smallest genetic unit: a single nucleotide of deoxyribonucleic acid or DNA.

A DNA nucleotide is composed of sugar and phosphate groups, and one of four nitrogenous bases: adenine, thymine, guanine, and cytosine, annotated in shorthand as A,T,G, and C. The sugar and phosphate groups form the DNA structural backbone, allowing nucleotides to concatenate into a long single strand of DNA, while the bases determine DNA sequence. The chemical properties of DNA allow bonds to form between the bases in order to create a double strand with two hydrogen bonds pairing A and T and three pairing C and G. Though different types of human cells can be very different in appearance and function, they contain the same genome, which consists of about three Giga bases or three billion base pairs of DNA. All the DNA in the cell would be about two meters in length if it were stretched out and must be condensed down to fit into cells as small as 10 micrometers across.

The DNA is first coiled into its canonical helix structure, and then wrapped around histone proteins to form a DNA protein structure called a nucleosome. These nucleosomes can be further wound and coiled together to create a compact structure that fits into the nucleus. During cell division, the DNA is organized into tightly wound chromosomes, 46 in total, with 23 coming from each parent. These chromosomes can be easily and accurately separated during cell division, guaranteeing that each new cell contains an exact copy of DNA. Outside of cell division, the DNA is decondensed in the nucleus, allowing greater accessibility.

The transcriptional machinery regulates expression of the approximately 20,000 genes, which, although they correspond to less than 2% of all genomic DNA, encode all the proteins necessary to build and run a human cell. So, to return to the original question, "how is it possible for all of human diversity to exist when we are 99.9% genetically similar?", it is important to remember that the 0.1% of DNA that varies, on average, between each of us, actually corresponds to about 3 million differences across the genome, with 20,000 of them on average falling into protein coding genes. Although that equals approximately one difference per gene, in reality, these differences are not evenly distributed across the coding regions.

Differences in DNA sequence are called variants, and those affecting a single position are called single nucleotide variants or SNVs. Common SNVs that occur in more than 1% of a population are called single nucleotide polymorphisms or SNPs. SNPs, along with larger scale sequence changes like deletions, duplications, and rearrangements, create all the richness of human genetic diversity at the population level.

This raises many questions on an individual level as well: How does DNA determine our traits? How can we understand what a gene does, and how variants in that gene might affect our lives? What can our DNA tell us about our risk, and our loved ones risk, of disease? How can information from our genomes improve our medical care? Understanding genetics allows us to apply the concepts of heritability and genetic variation to questions of human health and disease in our world today.
