---
title: "Chapter 10.3: Small Effect Sizes (Video Transcript)"
---

**Title**: Small effect sizes

**Presenter(s)**: Howard Edenberg, PhD (Department of Biochemistry and Molecular Biology, Indiana University School of Medicine)

**Howard Edenberg**:

A brief note about small effect sizes.

Hi. I'm Howard Edenberg from Indiana University. \[These are my personal views.\]

Psychiatric and substance use disorders are complex genetic disorders. The risk is affected by both genes and the environment. Neither works alone, and they interact, sometimes in very complex ways. No single genetic variant causes a complex trait such as a psychiatric or substance use disorder. Variations affecting many genes contribute to variations in physiology and these in turn contribute to variations in risk for the disorder, the course of the disorder, and the response to treatments.

Genome wide association studies (GWAS) are currently the best approach to identifying individual genetic variations that contribute to the risk of these and many other disorders. GWAS are unbiased analyses testing common variations across the genome to determine if they affect a trait. But because only about half of the total risk is contributed by genetic variation and that part is distributed among hundreds to thousands of genes, the effects of any one common variant are typically very small. So very large studies are needed to find these variants.

Since the effect of any one variant is very small, why bother to find them? Some have argued that discovering variants of such small effects is not helpful. I'll argue here that they're wrong. What we want to do is to reliably identify the hundreds of variants that contribute to risk even though each individual variant contributes only a tiny amount. There's much we can learn from this. There are some immediate uses of GWAS findings. The overall patterns of association can help predict part of the risk for the disorder through polygenic risk scores. They can show if traits are genetically related. They can examine potential causality by Mendelian Randomization. And they can help explain heterogeneity in many cases, if there are different patterns of variants among different people with the same overall disorder.

What else can we do once we've discovered many variants of small effect? The genetic variants and the pattern of them can lead us into biology. They can show us which genes are involved and which pathways are involved. These lead us into the physiology of the disorders and that in turn can lead us to better diagnosis, to rational drug discovery, and to personalized medicine, all of which I think will be very valuable.

The effect of a drug on a pathway is not limited by the effect size of the variant that led us to discover the pathway that's important in the disorder. Even if the variant is rare or the effect size of the variant is very small, if it leads us to a biological pathway, that pathway can be targeted by drugs that have a very large effect. The impact of a drug upon a pathway is in no way limited by the effect size of the variants that led us to understand the role of the pathway.

So I, for one, continue to think that using large GWAS to identify variants and genes that contribute to the risk for these and other disorders will prove of great value. Perhaps not immediately, but in the long run. Without such knowledge we're really flying blind when we look for new treatments.

Some thoughts about translating genome-wide association findings into new therapeutics for psychiatry have been discussed in a review article published a few years ago that's worth looking into. \[PMID: 27786187. PMCID: [PMC5676453](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5676453/)\]

Thanks for paying attention. Goodbye.
