---
title: "Tools/Software Resources"
---

+-------------------------------+-----------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+-------------------------------------------------+
| Analysis                      | Step                                          | Software                                                                                                                | Additional Tutorials                                                                                                                                                                                                                                                    | Language  | PubMed ID                                       |
+:==============================+:==============================================+:========================================================================================================================+:========================================================================================================================================================================================================================================================================+:==========+:================================================+
| General                       | File management/formatting                    | [SAMtools](http://www.htslib.org/)                                                                                      | [Manual](http://www.htslib.org/doc/samtools.html)                                                                                                                                                                                                                       | C; Python |                                                 |
+-------------------------------+-----------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+-------------------------------------------------+
| General                       | File management/formatting                    | [BCFtools](http://www.htslib.org/)                                                                                      | [Manual](http://samtools.github.io/bcftools/)\                                                                                                                                                                                                                          | C; Python |                                                 |
|                               |                                               |                                                                                                                         | [GitHub](https://github.com/samtools/bcftools)                                                                                                                                                                                                                          |           |                                                 |
+-------------------------------+-----------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+-------------------------------------------------+
| General                       | File management/formatting                    | [BEDtools](https://bedtools.readthedocs.io/en/latest/)                                                                  | [GitHub](https://github.com/arq5x/bedtools2)                                                                                                                                                                                                                            | C; C++    |                                                 |
+-------------------------------+-----------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+-------------------------------------------------+
| [**Chapter 5**](chapter5.qmd) |                                               |                                                                                                                         |                                                                                                                                                                                                                                                                         |           |                                                 |
+-------------------------------+-----------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+-------------------------------------------------+
| GWAS                          | Genotype calling and Imputation               | [MoChA](https://software.broadinstitute.org/software/mocha/)                                                            | [GitHub](https://github.com/freeseek/mocha)                                                                                                                                                                                                                             | C; R      | 29995854; 32581363                              |
+-------------------------------+-----------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+-------------------------------------------------+
| GWAS                          |                                               | Ricopili pipeline                                                                                                       |                                                                                                                                                                                                                                                                         |           |                                                 |
+-------------------------------+-----------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+-------------------------------------------------+
| GWAS                          | General; QC                                   | [PLINK1.9](https://zzz.bwh.harvard.edu/plink/plink2.shtml)/[PLINK2](https://www.cog-genomics.org/plink/2.0/)            |                                                                                                                                                                                                                                                                         |           |                                                 |
+-------------------------------+-----------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+-------------------------------------------------+
| GWAS                          | General; QC                                   |                                                                                                                         |                                                                                                                                                                                                                                                                         |           |                                                 |
+-------------------------------+-----------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+-------------------------------------------------+
| GWAS                          | Relatedness/Kinship                           | KING                                                                                                                    |                                                                                                                                                                                                                                                                         |           |                                                 |
+-------------------------------+-----------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+-------------------------------------------------+
| GWAS                          | Population Stratification/PCA                 | GENESIS/PCAiR                                                                                                           |                                                                                                                                                                                                                                                                         |           |                                                 |
+-------------------------------+-----------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+-------------------------------------------------+
| GWAS                          | Population Stratification/PCA                 | PC-Relate                                                                                                               |                                                                                                                                                                                                                                                                         |           |                                                 |
+-------------------------------+-----------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+-------------------------------------------------+
| GWAS                          | Local Ancestry and Admixture Inference        | [RFMix](https://github.com/slowkoni/rfmix)                                                                              | [GitHub](https://github.com/slowkoni/rfmix)                                                                                                                                                                                                                             | C++       | 23910464                                        |
+-------------------------------+-----------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+-------------------------------------------------+
| GWAS                          |                                               | [TRACTOR](https://github.com/Atkinson-Lab/Tractor-tutorial)                                                             | [GitHub](https://github.com/Atkinson-Lab/Tractor)                                                                                                                                                                                                                       |           | 33462486                                        |
+-------------------------------+-----------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+-------------------------------------------------+
| GWAS                          | Association Testing                           | [SAIGE](https://saigegit.github.io/SAIGE-doc/)                                                                          | [GitHub](https://github.com/weizhouUMICH/SAIGE); [More documentation](https://github.com/saigegit/SAIGE)                                                                                                                                                                | R; C++    | 30104761                                        |
+-------------------------------+-----------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+-------------------------------------------------+
| GWAS                          | Association Testing                           | BOLT-LMM                                                                                                                |                                                                                                                                                                                                                                                                         |           |                                                 |
+-------------------------------+-----------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+-------------------------------------------------+
| GWAS                          | Association Testing                           | REGENIE                                                                                                                 |                                                                                                                                                                                                                                                                         |           |                                                 |
+-------------------------------+-----------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+-------------------------------------------------+
|                               |                                               |                                                                                                                         |                                                                                                                                                                                                                                                                         |           |                                                 |
+-------------------------------+-----------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+-------------------------------------------------+
|                               |                                               |                                                                                                                         |                                                                                                                                                                                                                                                                         |           |                                                 |
+-------------------------------+-----------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+-------------------------------------------------+
| GWAS                          | Imputation panel                              | TOPMed                                                                                                                  |                                                                                                                                                                                                                                                                         |           |                                                 |
+-------------------------------+-----------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+-------------------------------------------------+
| GWAS                          | Imputation panel                              | 1000 Genomes                                                                                                            |                                                                                                                                                                                                                                                                         |           |                                                 |
+-------------------------------+-----------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+-------------------------------------------------+
| GWAS                          | Imputation panel                              | HRC                                                                                                                     |                                                                                                                                                                                                                                                                         |           |                                                 |
+-------------------------------+-----------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+-------------------------------------------------+
| GWAS                          | Power calculations                            | [genpwr](https://cran.r-project.org/web/packages/genpwr/vignettes/vignette.html)                                        |                                                                                                                                                                                                                                                                         | R         | 32721961                                        |
+-------------------------------+-----------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+-------------------------------------------------+
| GWAS                          | qqplot and Manhattan plot                     | qqman                                                                                                                   | [GitHub](https://github.com/stephenturner/qqman)                                                                                                                                                                                                                        | R         | [doi link](https://doi.org/10.21105/joss.00731) |
+-------------------------------+-----------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+-------------------------------------------------+
| [**Chapter 6**](chapter6.qmd) |                                               |                                                                                                                         |                                                                                                                                                                                                                                                                         |           |                                                 |
+-------------------------------+-----------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+-------------------------------------------------+
| PRS                           | PRS methods                                   | [PRS-CS](https://github.com/getian107/PRScs)                                                                            | GitHub                                                                                                                                                                                                                                                                  | Python    | 30992449                                        |
+-------------------------------+-----------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+-------------------------------------------------+
| PRS                           | PRS methods                                   | [PRS-CSx](https://github.com/getian107/PRScsx)                                                                          | [GitHub](https://github.com/getian107/PRScsx)                                                                                                                                                                                                                           | Python    | 35513724                                        |
+-------------------------------+-----------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+-------------------------------------------------+
| PRS                           | PRS methods                                   | [PRSice2](https://choishingwan.github.io/PRSice/)                                                                       | [Running PRSice-2](https://choishingwan.github.io/PRS-Tutorial/prsice/)                                                                                                                                                                                                 | R         | 31307061                                        |
+-------------------------------+-----------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+-------------------------------------------------+
| PRS                           | PRS methods                                   | [Lassosum](https://github.com/tshmak/lassosum/blob/master/lassosum_standalone.md#lassosum-standalone-version-for-linux) | [GitHub](https://github.com/tshmak/lassosum)                                                                                                                                                                                                                            | R; C++    | 28480976                                        |
+-------------------------------+-----------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+-------------------------------------------------+
| PRS                           | PRS methods                                   | [LDpred2](https://privefl.github.io/bigsnpr/articles/LDpred2.html)                                                      | [Manual](https://privefl.github.io/bigsnpr/articles/LDpred2.html)                                                                                                                                                                                                       | R         | 33326037                                        |
+-------------------------------+-----------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+-------------------------------------------------+
| PRS                           | PRS methods                                   | [SBayesR](https://cnsgenomics.com/software/gctb/#Overview)                                                              | [Manual](https://cnsgenomics.com/software/gctb/#SBayesRTutorial)                                                                                                                                                                                                        |           | 31704910                                        |
+-------------------------------+-----------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+-------------------------------------------------+
| PRS                           | PRS methods                                   | [MegaPRS](https://dougspeed.com/megaprs/)                                                                               |                                                                                                                                                                                                                                                                         | Python    | 34234142                                        |
+-------------------------------+-----------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+-------------------------------------------------+
| [Chapter 8](chapter8.qmd)     |                                               |                                                                                                                         |                                                                                                                                                                                                                                                                         |           |                                                 |
+-------------------------------+-----------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+-------------------------------------------------+
| SNP heritability              |                                               | GCTA-GREML                                                                                                              |                                                                                                                                                                                                                                                                         |           |                                                 |
+-------------------------------+-----------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+-------------------------------------------------+
| SNP heritability              |                                               | LDSC                                                                                                                    |                                                                                                                                                                                                                                                                         |           |                                                 |
+-------------------------------+-----------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+-------------------------------------------------+
| Genetic correlation           |                                               | LDSC                                                                                                                    |                                                                                                                                                                                                                                                                         |           |                                                 |
+-------------------------------+-----------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+-------------------------------------------------+
| Genetic correlation           |                                               | Genomic SEM                                                                                                             |                                                                                                                                                                                                                                                                         |           |                                                 |
+-------------------------------+-----------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+-------------------------------------------------+
| Genetic correlation           |                                               | [LAVA](https://github.com/josefin-werme/LAVA)                                                                           | [GitHub](https://github.com/josefin-werme/LAVA)                                                                                                                                                                                                                         | R         | 35288712                                        |
+-------------------------------+-----------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+-------------------------------------------------+
| TWAS                          | Transcriptomic Imputation                     | [PrediXcan](https://github.com/hakyimlab/MetaXcan)                                                                      | [GitHub](https://github.com/hakyimlab/MetaXcan); [Tutorial](https://github.com/hakyimlab/MetaXcan/wiki/Individual-level-PrediXcan:-introduction,-tutorials-and-manual)                                                                                                  | Python    | 26258848                                        |
+-------------------------------+-----------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+-------------------------------------------------+
| TWAS                          | Transcriptomic Imputation                     | [S-PrediXcan](https://github.com/hakyimlab/MetaXcan)                                                                    | [GitHub](https://github.com/hakyimlab/MetaXcan)                                                                                                                                                                                                                         | Python    | 29739930                                        |
+-------------------------------+-----------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+-------------------------------------------------+
| TWAS                          | Tissue models (GTEx, CommonMind, PsychENCODE) | [PredictDB](https://predictdb.org/)                                                                                     | [GTEx models](https://predictdb.org/post/2021/07/21/gtex-v8-models-on-eqtl-and-sqtl/); [PsychENCODE models](https://predictdb.org/post/2020/07/19/psychencode-brain-expression-models/); [CommonMind DLPFC models](https://github.com/laurahuckins/CMC_DLPFC_prediXcan) |           |                                                 |
+-------------------------------+-----------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+-------------------------------------------------+
|                               |                                               |                                                                                                                         |                                                                                                                                                                                                                                                                         |           |                                                 |
+-------------------------------+-----------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+-------------------------------------------------+
| Gene/Gene set identification  |                                               | MAGMA                                                                                                                   |                                                                                                                                                                                                                                                                         |           |                                                 |
+-------------------------------+-----------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+-------------------------------------------------+
| Gene/Gene set identification  |                                               | [H-MAGMA](https://github.com/thewonlab/H-MAGMA)                                                                         | [GitHub](https://github.com/thewonlab/H-MAGMA)                                                                                                                                                                                                                          |           |                                                 |
+-------------------------------+-----------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+-------------------------------------------------+
| Gene/Gene set identification  |                                               | E-MAGMA                                                                                                                 | [GitHub Tutorial](https://github.com/eskederks/eMAGMA-tutorial)                                                                                                                                                                                                         |           |                                                 |
+-------------------------------+-----------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+-------------------------------------------------+
| Gene/Gene set identification  |                                               | FUMA                                                                                                                    |                                                                                                                                                                                                                                                                         |           |                                                 |
+-------------------------------+-----------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+-------------------------------------------------+
| Gene/Gene set identification  |                                               | MAGMA                                                                                                                   |                                                                                                                                                                                                                                                                         |           |                                                 |
+-------------------------------+-----------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+-------------------------------------------------+
| Gene/Gene set identification  |                                               | PRSet                                                                                                                   |                                                                                                                                                                                                                                                                         |           |                                                 |
+-------------------------------+-----------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+-------------------------------------------------+
|                               |                                               |                                                                                                                         |                                                                                                                                                                                                                                                                         |           |                                                 |
+-------------------------------+-----------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+-------------------------------------------------+
| Software Tutorials            |                                               |                                                                                                                         |                                                                                                                                                                                                                                                                         |           |                                                 |
+-------------------------------+-----------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+-------------------------------------------------+
|                               |                                               | [MiXeR](https://github.com/precimed/mixer)                                                                              | [GitHub](https://github.com/precimed/mixer)                                                                                                                                                                                                                             | C         | 32427991; 31160569                              |
+-------------------------------+-----------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+-------------------------------------------------+
|                               |                                               | MTAG                                                                                                                    | [GitHub](https://github.com/JonJala/mtag)                                                                                                                                                                                                                               | Python    | 29292387                                        |
+-------------------------------+-----------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+-------------------------------------------------+
| Fine-mapping                  |                                               | [SuSiE](https://stephenslab.github.io/susie-paper/) (used with [coloc](https://chr1swallace.github.io/coloc/))          | [R package](https://stephenslab.github.io/susieR/)                                                                                                                                                                                                                      | R         | 37220626; 34587156                              |
+-------------------------------+-----------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+-------------------------------------------------+
| Fine-mapping                  |                                               | [coloc](https://chr1swallace.github.io/coloc/)                                                                          | [GitHub](https://github.com/chr1swallace/coloc); [R package](https://chr1swallace.github.io/coloc/)                                                                                                                                                                     | R         | 24830394; 32310995; 34587156                    |
+-------------------------------+-----------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+-------------------------------------------------+
|                               |                                               |                                                                                                                         |                                                                                                                                                                                                                                                                         |           |                                                 |
+-------------------------------+-----------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+-------------------------------------------------+
| EWAS                          | Epigenome-Wide Association Study              | [ewastools](https://github.com/hhhh5/ewastools)                                                                         | [GitHub](https://github.com/hhhh5/ewastools); [Workflow](https://hhhh5.github.io/ewastools/articles/exemplary_ewas.html)                                                                                                                                                | R         |                                                 |
+-------------------------------+-----------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+-------------------------------------------------+
