---
title: "Genomic SEM"
---

> In the following video, Dr. Grotzinger demonstrates how to run Genomic Structural Equation Modeling (Genomic SEM) using psychiatric traits as examples. The first part of the practical discusses how to estimate a user-specified model using genome-wide estimates, and the second half shows how to incorporate individual SNP effects for various multivariate methods.
>
> Description of Genomic SEM from Dr. Grotzinger:

> > "Genomic SEM is a general framework for modeling genetic covariance matrices produced by methods like LD score regression to then estimate any number of structural equation models that can be used to test hypotheses about the processes that gave rise to the data that we observe. It only requires your summary statistics, and those summary statistics can come from samples with unknown and varying degrees of sample overlap. What that means is that you can now estimate models for really rare traits that you would not otherwise observe in the same sample."

**Title**: Genomic SEM Tutorial

**Presenter(s)**: Andrew Grotzinger, PhD (Institute for Behavioral Genetics, University of Colorado Boulder)

**Level**: Intermediate

**Length**: 14:59

```{r, echo=FALSE}
library("vembedr")
embed_url("https://www.youtube.com/watch?v=tBWkC2wCYuA")
```

Link to video transcript [here](software_genomicSEM_transcript.qmd).

[Link to tutorial scripts and datasets](https://utexas.app.box.com/s/nmkyfd17lq0aux2vuo735ohy00tl74qt).

For more information and tutorials on Genomic SEM see [Chapter 9.3](chapter9.qmd#sec-section3).
